services:
  # THE FORGOTTEN SERVER SETUP
  new_database:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'adventures'
      MYSQL_USER: 'tfs_manager'
      MYSQL_ROOT_PASSWORD: 'mauFJcuf5dhRMQrjj'
      MYSQL_PASSWORD: 'mauFJcuf5dhRMQrjj'
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
    ]
    expose:
        - "40000"
    ports:
        - "40000:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "tfs_manager", "-pmauFJcuf5dhRMQrjj"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  new_phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40002"
    ports:
      - "40002:80"
    environment:
      - PMA_HOST=new_database
      - PMA_PORT=3306
    networks:
      - db-network

  new_server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7171:7171"
      - "7172:7172"
      - "7173:7173"
      - "8080:8080"
    depends_on:
      new_database:
        condition: service_healthy
    volumes:
      - ./logger/tfs_server/logs:/var/log
      - ./data:/srv/data
      - ./config.lua:/srv/config.lua
      - ./key.pem:/srv/key.pem
    networks:
      - db-network

networks:
  db-network:
