-- Generated by tools/export_nbq_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/bosses/necromancer.ts
-- NBQ script callbacks are preserved in NBQMonsterRegistry.byKind and still need a dedicated Lua port.
local mType = Game.createMonsterType("Necromancer")
local monster = {}

monster.name = "Necromancer"
monster.experience = 4500
monster.outfit = {
  lookType = 26,
}
monster.health = 9550
monster.maxHealth = 9550
monster.race = "undead"
monster.speed = 240
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
  boss = true,
}
monster.loot = {
  {id = 124, chance = 40000, maxCount = 1},
  {id = 76, chance = 5000, maxCount = 1},
  {id = 82, chance = 4000, maxCount = 1},
  {id = 113, chance = 4000, maxCount = 1},
  {id = 150, chance = 4000, maxCount = 1},
  {id = 333, chance = 4000, maxCount = 1},
  {id = 115, chance = 1000, maxCount = 1},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -155,
    maxDamage = -20
  },
}
monster.defenses = {
  defense = 14,
  armor = 14,
}
monster.elements = {
  {
    type = COMBAT_UNDEFINEDDAMAGE,
    percent = 50
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 50
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 50
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 100
  },
}

mType:register(monster)
