-- Generated by tools/export_nbq_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/deathknight.ts
local mType = Game.createMonsterType("Death Knight")
local monster = {}

monster.name = "Death Knight"
monster.experience = 71
monster.outfit = {
  lookType = 10,
}
monster.health = 354
monster.maxHealth = 354
monster.race = "blood"
monster.speed = 186
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 36, chance = 40000, maxCount = 1},
  {id = 81, chance = 5000, maxCount = 1},
  {id = 86, chance = 5000, maxCount = 1},
  {id = 112, chance = 2000, maxCount = 1},
  {id = 75, chance = 20000, maxCount = 1},
  {id = 146, chance = 5000, maxCount = 1},
  {id = 92, chance = 12000, maxCount = 22},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -49,
    maxDamage = -16
  },
}
monster.defenses = {
  defense = 4,
  armor = 4,
}

mType:register(monster)
