-- Generated by tools/export_nbq_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/skeleton_crusader.ts
local mType = Game.createMonsterType("Skeleton Crusader")
local monster = {}

monster.name = "Skeleton Crusader"
monster.experience = 5295
monster.outfit = {
  lookType = 36,
}
monster.health = 1619
monster.maxHealth = 1619
monster.race = "blood"
monster.speed = 73
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 25000, maxCount = 1},
  {id = 200, chance = 1000, maxCount = 2},
  {id = 209, chance = 2000, maxCount = 1},
  {id = 212, chance = 2000, maxCount = 1},
  {id = 155, chance = 2000, maxCount = 1},
  {id = 140, chance = 2000, maxCount = 1},
  {id = 203, chance = 2000, maxCount = 1},
  {id = 153, chance = 2000, maxCount = 1},
  {id = 337, chance = 2000, maxCount = 1},
  {id = 92, chance = 60000, maxCount = 60},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -579,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 27,
  armor = 27,
}
monster.elements = {
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 65
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 45
  },
}

mType:register(monster)
