-- Generated by tools/export_nbq_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/skeleton_guardian.ts
local mType = Game.createMonsterType("Shadowveil Guardian")
local monster = {}

monster.name = "Shadowveil Guardian"
monster.experience = 30218
monster.outfit = {
  lookType = 43,
}
monster.health = 4887
monster.maxHealth = 4887
monster.race = "undead"
monster.speed = 107
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 15000, maxCount = 1},
  {id = 200, chance = 8000, maxCount = 2},
  {id = 158, chance = 2000, maxCount = 1},
  {id = 401, chance = 2000, maxCount = 1},
  {id = 341, chance = 2000, maxCount = 1},
  {id = 242, chance = 2000, maxCount = 1},
  {id = 202, chance = 2000, maxCount = 1},
  {id = 196, chance = 2000, maxCount = 1},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -816,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 34,
  armor = 34,
}
monster.elements = {
  {
    type = COMBAT_UNDEFINEDDAMAGE,
    percent = 60
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 40
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 30
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 30
  },
  {
    type = COMBAT_EARTHDAMAGE,
    percent = 30
  },
}

mType:register(monster)
