-- Generated by tools/export_nbq_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/spellweaver_spider.ts
local mType = Game.createMonsterType("Spellweaver Spider")
local monster = {}

monster.name = "Spellweaver Spider"
monster.experience = 3538
monster.outfit = {
  lookType = 52,
}
monster.health = 2144
monster.maxHealth = 2144
monster.race = "blood"
monster.speed = 60
monster.runHealth = 25
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 20000, maxCount = 1},
  {id = 200, chance = 3000, maxCount = 1},
  {id = 209, chance = 2000, maxCount = 1},
  {id = 212, chance = 2000, maxCount = 1},
  {id = 111, chance = 10000, maxCount = 1},
  {id = 156, chance = 2000, maxCount = 1},
  {id = 338, chance = 2000, maxCount = 1},
  {id = 228, chance = 2000, maxCount = 1},
  {id = 197, chance = 2000, maxCount = 1},
  {id = 92, chance = 12000, maxCount = 100},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -32,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 30,
  armor = 30,
}
monster.elements = {
  {
    type = COMBAT_UNDEFINEDDAMAGE,
    percent = 100
  },
}

mType:register(monster)
