-- Generated by tools/export_nbq_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/temple_mob.ts
local mType = Game.createMonsterType("Temple Mob")
local monster = {}

monster.name = "Temple Mob"
monster.experience = 13569
monster.health = 3053
monster.maxHealth = 3053
monster.race = "blood"
monster.speed = 72
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 15000, maxCount = 1},
  {id = 200, chance = 3000, maxCount = 1},
  {id = 158, chance = 2000, maxCount = 1},
  {id = 401, chance = 2000, maxCount = 1},
  {id = 341, chance = 2000, maxCount = 1},
  {id = 242, chance = 2000, maxCount = 1},
  {id = 202, chance = 2000, maxCount = 1},
  {id = 196, chance = 2000, maxCount = 1},
  {id = 92, chance = 10000, maxCount = 60},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -253,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 73,
  armor = 55,
}

mType:register(monster)
