-- Generated by tools/export_nbq_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/undead_rat.ts
local mType = Game.createMonsterType("Undead Rat")
local monster = {}

monster.name = "Undead Rat"
monster.experience = 300
monster.outfit = {
  lookType = 30,
}
monster.health = 320
monster.maxHealth = 320
monster.race = "undead"
monster.speed = 200
monster.runHealth = 0
monster.changeTarget = {
  interval = 2000,
  chance = 70,
}
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 60000, maxCount = 1},
  {id = 87, chance = 5000, maxCount = 1},
  {id = 76, chance = 8000, maxCount = 1},
  {id = 148, chance = 3000, maxCount = 1},
  {id = 331, chance = 5000, maxCount = 1},
  {id = 92, chance = 46000, maxCount = 26},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -70,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 11,
  armor = 9,
}

mType:register(monster)
