-- Generated by tools/export_nbq_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/wraith.ts
local mType = Game.createMonsterType("Wraith")
local monster = {}

monster.name = "Wraith"
monster.experience = 1850
monster.outfit = {
  lookType = 59,
}
monster.health = 2095
monster.maxHealth = 2095
monster.speed = 190
monster.runHealth = 0
monster.changeTarget = {
  interval = 5000,
  chance = 20,
}
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 60000, maxCount = 1},
  {id = 91, chance = 3000, maxCount = 1},
  {id = 141, chance = 1000, maxCount = 1},
  {id = 149, chance = 1000, maxCount = 1},
  {id = 150, chance = 2000, maxCount = 1},
  {id = 333, chance = 2000, maxCount = 1},
  {id = 76, chance = 5000, maxCount = 1},
  {id = 82, chance = 3000, maxCount = 1},
  {id = 113, chance = 2000, maxCount = 1},
  {id = 92, chance = 56000, maxCount = 70},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -125,
    maxDamage = -60
  },
  {
    name = "combat",
    type = COMBAT_ICEDAMAGE,
    chance = 24,
    interval = 2400,
    target = true,
    range = 5,
    minDamage = -188,
    maxDamage = -97,
    effect = 138,
    condition = {
      type = CONDITION_FREEZING,
      duration = 4000
    }
  },
}
monster.defenses = {
  defense = 11,
  armor = 11,
}

mType:register(monster)
