-- Generated by tools/export_nbq_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/zombie.ts
local mType = Game.createMonsterType("Zombie")
local monster = {}

monster.name = "Zombie"
monster.experience = 1200
monster.outfit = {
  lookType = 62,
}
monster.health = 837
monster.maxHealth = 837
monster.race = "undead"
monster.speed = 240
monster.runHealth = 0
monster.changeTarget = {
  interval = 3000,
  chance = 20,
}
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 40000, maxCount = 1},
  {id = 76, chance = 5200, maxCount = 4},
  {id = 82, chance = 3000, maxCount = 2},
  {id = 113, chance = 18000, maxCount = 2},
  {id = 150, chance = 5000, maxCount = 1},
  {id = 333, chance = 37000, maxCount = 1},
  {id = 92, chance = 60000, maxCount = 36},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -134,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 15,
  armor = 11,
}

mType:register(monster)
