-- Generated by tools/export_nbq_content.mjs. Do not edit by hand.
NBQItemRegistry = {
  byId = {
    ["1"] = {
      kind = "backpack",
      name = "Backpack",
      slotType = "backpack",
      flags = {},
      stackable = false,
      attributes = {
        description = "A standard backpack."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["20"] = {
      kind = "firefox",
      name = "Firefox",
      slotType = "armor",
      flags = {},
      stackable = false,
      attributes = {
        defense = 1
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["21"] = {
      kind = "player-body",
      name = "Cloth Armor",
      slotType = "armor",
      requiredLevel = 1,
      flags = {},
      stackable = false,
      attributes = {
        defense = 1
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["22"] = {
      kind = "leatherarmor",
      name = "Leather Armor",
      slotType = "armor",
      requiredLevel = 1,
      price = 2,
      flags = {},
      stackable = false,
      attributes = {
        defense = 3
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["23"] = {
      kind = "mailarmor",
      name = "Mail Armor",
      slotType = "armor",
      requiredLevel = 3,
      price = 3,
      flags = {},
      stackable = false,
      attributes = {
        defense = 5
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["24"] = {
      kind = "platearmor",
      name = "Plate Armor",
      slotType = "armor",
      requiredLevel = 5,
      price = 4,
      flags = {},
      stackable = false,
      attributes = {
        defense = 10
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["25"] = {
      kind = "redarmor",
      name = "Ruby Armor",
      slotType = "armor",
      requiredLevel = 7,
      price = 5,
      flags = {},
      stackable = false,
      attributes = {
        defense = 15
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["26"] = {
      kind = "goldenarmor",
      name = "Golden Armor",
      slotType = "armor",
      requiredLevel = 10,
      price = 6,
      flags = {},
      stackable = false,
      attributes = {
        defense = 20
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["35"] = {
      kind = "flask",
      name = "Health Potion",
      requiredLevel = 50,
      flags = {
        "consumable"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "A health potion that healths <span style=\"color:red\">+40HP</span>. Cooldown 2s."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["36"] = {
      kind = "burger",
      name = "Burger",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["37"] = {
      kind = "chest",
      name = "Chest",
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["38"] = {
      kind = "firefoxpotion",
      name = "Firefoxpotion",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["39"] = {
      kind = "cake",
      name = "Cake",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["60"] = {
      kind = "dagger",
      name = "Dagger",
      slotType = "weapon",
      requiredLevel = 1,
      flags = {},
      stackable = false,
      attributes = {
        attack = 2
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["61"] = {
      kind = "sword",
      name = "Sword",
      slotType = "weapon",
      requiredLevel = 1,
      price = 2,
      flags = {},
      stackable = false,
      attributes = {
        attack = 3
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["62"] = {
      kind = "morningstar",
      name = "Morning Star",
      slotType = "weapon",
      requiredLevel = 3,
      price = 4,
      flags = {},
      stackable = false,
      attributes = {
        attack = 7
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["63"] = {
      kind = "axe",
      name = "Axe",
      slotType = "weapon",
      requiredLevel = 2,
      price = 3,
      flags = {},
      stackable = false,
      attributes = {
        attack = 5
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["64"] = {
      kind = "bluesword",
      name = "Magic Sword",
      slotType = "weapon",
      requiredLevel = 5,
      price = 5,
      flags = {},
      stackable = false,
      attributes = {
        attack = 10
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["65"] = {
      kind = "redsword",
      name = "Red Sword",
      slotType = "weapon",
      requiredLevel = 7,
      price = 5,
      flags = {},
      stackable = false,
      attributes = {
        attack = 15
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["66"] = {
      kind = "goldensword",
      name = "Golden Sword",
      slotType = "weapon",
      requiredLevel = 16,
      price = 6,
      flags = {},
      stackable = false,
      attributes = {
        attack = 20
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["67"] = {
      kind = "nanopotion",
      name = "Nanopotion",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["68"] = {
      kind = "gemruby",
      name = "Gemruby",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["69"] = {
      kind = "gememerald",
      name = "Gememerald",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["70"] = {
      kind = "gemamethyst",
      name = "Gemamethyst",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["71"] = {
      kind = "gemtopaz",
      name = "Gemtopaz",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["74"] = {
      kind = "scrollupgradelow",
      name = "Upgrade scroll",
      requiredLevel = 3,
      price = 15,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Upgrade low class items. The chances for a successful upgrade varies depending on the item's level."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["75"] = {
      kind = "scrollupgrademedium",
      name = "Upgrade scroll",
      requiredLevel = 6,
      price = 35,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Upgrade medium class items. The chances for a successful upgrade varies depending on the item's level."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["76"] = {
      kind = "scrollupgradehigh",
      name = "Superior upgrade scroll",
      requiredLevel = 15,
      price = 100,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Upgrade high class item. The chances for a successful upgrade varies depending on the item's level."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["77"] = {
      kind = "blueaxe",
      name = "Frozen Axe",
      slotType = "weapon",
      requiredLevel = 18,
      price = 8,
      flags = {},
      stackable = false,
      attributes = {
        attack = 24
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["78"] = {
      kind = "frozenarmor",
      name = "Sapphire Armor",
      slotType = "armor",
      requiredLevel = 26,
      price = 10,
      flags = {},
      stackable = false,
      attributes = {
        defense = 30
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["79"] = {
      kind = "gemsapphire",
      name = "Gemsapphire",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["80"] = {
      kind = "ringbronze",
      name = "Bronze Ring",
      slotType = "ring1",
      requiredLevel = 1,
      price = 25,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["81"] = {
      kind = "ringsilver",
      name = "Silver Ring",
      slotType = "ring1",
      requiredLevel = 9,
      price = 35,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["82"] = {
      kind = "ringgold",
      name = "Gold Ring",
      slotType = "ring1",
      requiredLevel = 16,
      price = 45,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["83"] = {
      kind = "hornedarmor",
      name = "Horned Armor",
      slotType = "armor",
      requiredLevel = 22,
      price = 9,
      flags = {},
      stackable = false,
      attributes = {
        defense = 28
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["85"] = {
      kind = "beltleather",
      name = "Leather Belt",
      slotType = "belt",
      requiredLevel = 4,
      price = 1,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["86"] = {
      kind = "beltplated",
      name = "Plated Belt",
      slotType = "belt",
      requiredLevel = 9,
      price = 3,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["87"] = {
      kind = "bluearmor",
      name = "Frozen Armor",
      slotType = "armor",
      requiredLevel = 18,
      price = 8,
      flags = {},
      stackable = false,
      attributes = {
        defense = 24
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["91"] = {
      kind = "beltfrozen",
      name = "Sapphire Belt",
      slotType = "belt",
      requiredLevel = 24,
      price = 5,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["92"] = {
      kind = "gold",
      name = "Gold Coins",
      flags = {},
      stackable = true,
      maxStack = 30000,
      source = "packages/common/game/itemsData.ts"
    },
    ["94"] = {
      kind = "skeletonkey",
      name = "Skeleton Key",
      flags = {
        "quest"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["95"] = {
      kind = "raiblockstl",
      name = "Raiblocks artifact",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["96"] = {
      kind = "raiblockstr",
      name = "Raiblocks artifact",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["97"] = {
      kind = "raiblocksbl",
      name = "Raiblocks artifact",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["98"] = {
      kind = "raiblocksbr",
      name = "Raiblocks artifact",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["100"] = {
      kind = "frozensword",
      name = "Sapphire Sword",
      slotType = "weapon",
      requiredLevel = 26,
      price = 10,
      flags = {},
      stackable = false,
      attributes = {
        attack = 30
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["107"] = {
      kind = "bluemorningstar",
      name = "Frozen Morning Star",
      slotType = "weapon",
      requiredLevel = 20,
      price = 8,
      flags = {},
      stackable = false,
      attributes = {
        attack = 26
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["110"] = {
      kind = "rejuvenationpotion",
      name = "Rejuvenationpotion",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["111"] = {
      kind = "poisonpotion",
      name = "Poisonpotion",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["112"] = {
      kind = "amuletsilver",
      name = "Silver Amulet",
      slotType = "amulet",
      requiredLevel = 9,
      price = 25,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["113"] = {
      kind = "amuletgold",
      name = "Gold Amulet",
      slotType = "amulet",
      requiredLevel = 20,
      price = 35,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["115"] = {
      kind = "ringnecromancer",
      name = "Necromancer Death Wish",
      slotType = "ring1",
      requiredLevel = 38,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["116"] = {
      kind = "amuletcow",
      name = "Holy Cow King Talisman",
      slotType = "amulet",
      requiredLevel = 34,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["117"] = {
      kind = "ringraistone",
      name = "Rai Stone",
      slotType = "ring1",
      requiredLevel = 18,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["118"] = {
      kind = "scrollupgradeblessed",
      name = "Blessed upgrade scroll",
      requiredLevel = 15,
      price = 250,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Upgrade high class item. The chances for a successful upgrade varies depending on the item's level. Blessed scrolls gives a higher chance of successful upgrade."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["121"] = {
      kind = "diamondsword",
      name = "Diamond Sword",
      slotType = "weapon",
      requiredLevel = 34,
      price = 100,
      flags = {},
      stackable = false,
      attributes = {
        attack = 38
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["122"] = {
      kind = "wirtleg",
      name = "Wirt's leg",
      slotType = "weapon",
      requiredLevel = 1,
      price = 3,
      flags = {},
      stackable = false,
      attributes = {
        attack = 5
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["123"] = {
      kind = "skeletonkingcage",
      name = "Skeleton King's thoracic cage",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "The thoracic cage of the Skeleton King. An unknown magic is still being emitted from the remains. Combined with other ingredients at the anvil, it will open a secret area, lv.45 required to enter"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["124"] = {
      kind = "necromancerheart",
      name = "Necromancer's heart",
      flags = {
        "quest",
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "The heart of the Necromancer. An unknown magic is still being emitted from the remains. . Combined with other ingredients at the anvil, it will open a secret area, lv.45 required to enter"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["126"] = {
      kind = "ringfountain",
      name = "Fountain of Youth",
      slotType = "ring1",
      requiredLevel = 26,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["127"] = {
      kind = "diamondarmor",
      name = "Diamond Armor",
      slotType = "armor",
      requiredLevel = 36,
      price = 100,
      flags = {},
      stackable = false,
      attributes = {
        defense = 36
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["128"] = {
      kind = "emeraldarmor",
      name = "Emerald Armor",
      slotType = "armor",
      requiredLevel = 48,
      price = 35,
      flags = {},
      stackable = false,
      attributes = {
        defense = 42
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["129"] = {
      kind = "beltdiamond",
      name = "Diamond Belt",
      slotType = "belt",
      requiredLevel = 34,
      price = 85,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["130"] = {
      kind = "cape",
      name = "Cape",
      slotType = "cape",
      requiredLevel = 20,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["131"] = {
      kind = "capehigh",
      name = "Cape High",
      slotType = "cape",
      requiredLevel = 60,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["132"] = {
      kind = "ringminotaur",
      name = "Hell Freeze",
      slotType = "ring1",
      requiredLevel = 36,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["133"] = {
      kind = "minotauraxe",
      name = "Minotaur Axe",
      slotType = "weapon",
      requiredLevel = 36,
      price = 125,
      flags = {},
      stackable = false,
      attributes = {
        attack = 44
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["134"] = {
      kind = "beltminotaur",
      name = "Minotaur Belt",
      slotType = "belt",
      requiredLevel = 38,
      price = 110,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["136"] = {
      kind = "chestblue",
      name = "Blue Chest",
      requiredLevel = 45,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "The chest may contain a very precious item."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["137"] = {
      kind = "cowkinghorn",
      name = "Cow King's horn",
      flags = {
        "quest",
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "The horn of the Cow King. An unknown magic is still being emitted from the remains."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["138"] = {
      kind = "amuletfrozen",
      name = "Frozen Heart",
      slotType = "amulet",
      requiredLevel = 40,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["139"] = {
      kind = "bananopotion",
      name = "Bananopotion",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["140"] = {
      kind = "templararmor",
      name = "Templar Armor",
      slotType = "armor",
      requiredLevel = 50,
      price = 38,
      flags = {},
      stackable = false,
      attributes = {
        defense = 44
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["141"] = {
      kind = "belthorned",
      name = "Horned Belt",
      slotType = "belt",
      requiredLevel = 26,
      price = 5,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["142"] = {
      kind = "scrolltransmute",
      name = "Transmute scroll",
      requiredLevel = 30,
      price = 250,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Transmute a ring or an amulet and generate new random stats or an item to have a chance of making it unique. The chances of transmuting stats is fixed while the chances of getting a unique varies. There is a 25% chance your item will be burned during the transmutation."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["143"] = {
      kind = "shieldwood",
      name = "Wood Shield",
      slotType = "shield",
      requiredLevel = 1,
      price = 2,
      flags = {},
      stackable = false,
      attributes = {
        defense = 2
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["144"] = {
      kind = "shieldiron",
      name = "Iron Shield",
      slotType = "shield",
      requiredLevel = 3,
      price = 3,
      flags = {},
      stackable = false,
      attributes = {
        defense = 3
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["145"] = {
      kind = "shieldplate",
      name = "Plate Shield",
      slotType = "shield",
      requiredLevel = 5,
      price = 4,
      flags = {},
      stackable = false,
      attributes = {
        defense = 5
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["146"] = {
      kind = "shieldred",
      name = "Red Shield",
      slotType = "shield",
      requiredLevel = 7,
      price = 5,
      flags = {},
      stackable = false,
      attributes = {
        defense = 7
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["147"] = {
      kind = "shieldgolden",
      name = "Golden Shield",
      slotType = "shield",
      requiredLevel = 10,
      price = 6,
      flags = {},
      stackable = false,
      attributes = {
        defense = 10
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["148"] = {
      kind = "shieldblue",
      name = "Frozen Shield",
      slotType = "shield",
      requiredLevel = 18,
      price = 8,
      flags = {},
      stackable = false,
      attributes = {
        defense = 12
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["149"] = {
      kind = "shieldhorned",
      name = "Horned Shield",
      slotType = "shield",
      requiredLevel = 22,
      price = 9,
      flags = {},
      stackable = false,
      attributes = {
        defense = 14
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["150"] = {
      kind = "shieldfrozen",
      name = "Sapphire Shield",
      slotType = "shield",
      requiredLevel = 26,
      price = 10,
      flags = {},
      stackable = false,
      attributes = {
        defense = 16
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["151"] = {
      kind = "shielddiamond",
      name = "Diamond Shield",
      slotType = "shield",
      requiredLevel = 36,
      price = 95,
      flags = {},
      stackable = false,
      attributes = {
        defense = 22
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["152"] = {
      kind = "emeraldsword",
      name = "Emerald Sword",
      slotType = "weapon",
      requiredLevel = 48,
      price = 35,
      flags = {},
      stackable = false,
      attributes = {
        attack = 56
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["153"] = {
      kind = "shieldtemplar",
      name = "Templar Shield",
      slotType = "shield",
      requiredLevel = 50,
      price = 32,
      flags = {},
      stackable = false,
      attributes = {
        defense = 28
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["154"] = {
      kind = "executionersword",
      name = "Executioner Sword",
      slotType = "weapon",
      requiredLevel = 50,
      price = 35,
      flags = {},
      stackable = false,
      attributes = {
        attack = 56
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["155"] = {
      kind = "templarsword",
      name = "Templar Sword",
      slotType = "weapon",
      requiredLevel = 52,
      price = 38,
      flags = {},
      stackable = false,
      attributes = {
        attack = 58
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["156"] = {
      kind = "dragonsword",
      name = "Dragon Sword",
      slotType = "weapon",
      requiredLevel = 54,
      price = 40,
      flags = {},
      stackable = false,
      attributes = {
        attack = 58
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["157"] = {
      kind = "moonsword",
      name = "Moon Sword",
      slotType = "weapon",
      requiredLevel = 26,
      price = 50,
      flags = {},
      stackable = false,
      attributes = {
        attack = 30
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["158"] = {
      kind = "mysticalsword",
      name = "Mystical Sword",
      slotType = "weapon",
      requiredLevel = 56,
      price = 85,
      flags = {},
      stackable = false,
      attributes = {
        attack = 62
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["159"] = {
      kind = "spikeglaive",
      name = "Spike Glaive",
      slotType = "weapon",
      requiredLevel = 60,
      price = 250,
      flags = {},
      stackable = false,
      attributes = {
        attack = 68
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["160"] = {
      kind = "eclypsedagger",
      name = "Eclypse Dagger",
      slotType = "weapon",
      requiredLevel = 60,
      price = 250,
      flags = {},
      stackable = false,
      attributes = {
        attack = 60
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["161"] = {
      kind = "rune-sat",
      name = "SAT Rune",
      requiredLevel = 1,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["162"] = {
      kind = "rune-al",
      name = "AL Rune",
      requiredLevel = 2,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["163"] = {
      kind = "rune-bul",
      name = "BUL Rune",
      requiredLevel = 3,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["164"] = {
      kind = "rune-nan",
      name = "NAN Rune",
      requiredLevel = 4,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["165"] = {
      kind = "rune-mir",
      name = "MIR Rune",
      requiredLevel = 6,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["166"] = {
      kind = "rune-gel",
      name = "GEL Rune",
      requiredLevel = 8,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["167"] = {
      kind = "rune-do",
      name = "DO Rune",
      requiredLevel = 10,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["168"] = {
      kind = "rune-ban",
      name = "BAN Rune",
      requiredLevel = 12,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["169"] = {
      kind = "rune-vie",
      name = "VIE Rune",
      requiredLevel = 14,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["170"] = {
      kind = "rune-um",
      name = "UM Rune",
      requiredLevel = 16,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["171"] = {
      kind = "rune-hex",
      name = "HEX Rune",
      requiredLevel = 18,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["172"] = {
      kind = "rune-zal",
      name = "ZAL Rune",
      requiredLevel = 20,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["173"] = {
      kind = "rune-sol",
      name = "SOL Rune",
      requiredLevel = 22,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["174"] = {
      kind = "rune-eth",
      name = "ETH Rune",
      requiredLevel = 24,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["175"] = {
      kind = "rune-btc",
      name = "BTC Rune",
      requiredLevel = 26,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["176"] = {
      kind = "rune-vax",
      name = "VAX Rune",
      requiredLevel = 28,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["177"] = {
      kind = "rune-por",
      name = "POR Rune",
      requiredLevel = 30,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["178"] = {
      kind = "rune-las",
      name = "LAS Rune",
      requiredLevel = 32,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["179"] = {
      kind = "rune-dur",
      name = "DUR Rune",
      requiredLevel = 34,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["180"] = {
      kind = "rune-fal",
      name = "FAL Rune",
      requiredLevel = 36,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["181"] = {
      kind = "rune-kul",
      name = "KUL Rune",
      requiredLevel = 38,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["182"] = {
      kind = "rune-mer",
      name = "MER Rune",
      requiredLevel = 41,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["183"] = {
      kind = "rune-qua",
      name = "QUA Rune",
      requiredLevel = 44,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["184"] = {
      kind = "rune-gul",
      name = "GUL Rune",
      requiredLevel = 47,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["185"] = {
      kind = "rune-ber",
      name = "BER Rune",
      requiredLevel = 50,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["186"] = {
      kind = "rune-cham",
      name = "CHAM Rune",
      requiredLevel = 53,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["187"] = {
      kind = "rune-tor",
      name = "TOR Rune",
      requiredLevel = 56,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["188"] = {
      kind = "rune-xno",
      name = "XNO Rune",
      requiredLevel = 59,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["189"] = {
      kind = "rune-jah",
      name = "JAH Rune",
      requiredLevel = 62,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["190"] = {
      kind = "rune-shi",
      name = "SHI Rune",
      requiredLevel = 65,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["191"] = {
      kind = "rune-vod",
      name = "VOD Rune",
      requiredLevel = 68,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["192"] = {
      kind = "stonesocket",
      name = "Socket Stone",
      requiredLevel = 51,
      price = 250,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Creates a random number of sockets in a non-socketed item. If all sockets are empty, you can re-roll sockets up to 4 on unique items or 3 for normal items<br/><br/>If the item already has sockets, the stone will attempt to remove the last item from its socket. There is 50% chance for the extracting item to be burned."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["194"] = {
      kind = "ringbalrog",
      name = "Ring of Power",
      slotType = "ring1",
      requiredLevel = 58,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["195"] = {
      kind = "shieldexecutioner",
      name = "Executioner Shield",
      slotType = "shield",
      requiredLevel = 48,
      price = 30,
      flags = {},
      stackable = false,
      attributes = {
        defense = 28
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["196"] = {
      kind = "shieldmystical",
      name = "Mystical Shield",
      slotType = "shield",
      requiredLevel = 54,
      price = 80,
      flags = {},
      stackable = false,
      attributes = {
        defense = 32
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["197"] = {
      kind = "shielddragon",
      name = "Dragon Shield",
      slotType = "shield",
      requiredLevel = 50,
      price = 35,
      flags = {},
      stackable = false,
      attributes = {
        defense = 28
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["198"] = {
      kind = "shielddemon",
      name = "Demon Shield",
      slotType = "shield",
      requiredLevel = 54,
      price = 120,
      flags = {},
      stackable = false,
      attributes = {
        defense = 32
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["199"] = {
      kind = "shieldemerald",
      name = "Emerald Shield",
      slotType = "shield",
      requiredLevel = 48,
      price = 30,
      flags = {},
      stackable = false,
      attributes = {
        defense = 26
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["200"] = {
      kind = "scrollupgradelegendary",
      name = "Legendary upgrade scroll",
      requiredLevel = 48,
      price = 250,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Upgrade legendary class item. The chances for a successful upgrade varies depending on the item's level."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["201"] = {
      kind = "beltemerald",
      name = "Emerald Belt",
      slotType = "belt",
      requiredLevel = 50,
      price = 28,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["202"] = {
      kind = "beltmystical",
      name = "Mystical Belt",
      slotType = "belt",
      requiredLevel = 54,
      price = 75,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["203"] = {
      kind = "belttemplar",
      name = "Templar Belt",
      slotType = "belt",
      requiredLevel = 52,
      price = 30,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["204"] = {
      kind = "beltdemon",
      name = "Demon Belt",
      slotType = "belt",
      requiredLevel = 54,
      price = 115,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["205"] = {
      kind = "beltmoon",
      name = "Moon Belt",
      slotType = "belt",
      requiredLevel = 54,
      price = 42,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["206"] = {
      kind = "scrollupgradesacred",
      name = "Sacred upgrade scroll",
      requiredLevel = 48,
      price = 3500,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Upgrade legendary class item. The chances for a successful upgrade varies depending on the item's level. Sacred scrolls gives a higher chance of successful upgrade."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["207"] = {
      kind = "beltexecutioner",
      name = "Executioner Belt",
      slotType = "belt",
      requiredLevel = 50,
      price = 30,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["208"] = {
      kind = "shieldmoon",
      name = "Moon Shield",
      slotType = "shield",
      requiredLevel = 52,
      price = 45,
      flags = {},
      stackable = false,
      attributes = {
        defense = 30
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["209"] = {
      kind = "ringplatinum",
      name = "Platinum Ring",
      slotType = "ring1",
      requiredLevel = 48,
      price = 65,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["210"] = {
      kind = "ringconqueror",
      name = "Conqueror Ring",
      slotType = "ring1",
      requiredLevel = 50,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["211"] = {
      kind = "ringheaven",
      name = "Touch of Heaven Ring",
      slotType = "ring1",
      requiredLevel = 50,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["212"] = {
      kind = "amuletplatinum",
      name = "Platinum Amulet",
      slotType = "amulet",
      requiredLevel = 48,
      price = 65,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["213"] = {
      kind = "ringwizard",
      name = "Wizard Ring",
      slotType = "ring1",
      requiredLevel = 50,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["214"] = {
      kind = "ringmystical",
      name = "Oculus",
      slotType = "ring1",
      requiredLevel = 54,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["215"] = {
      kind = "amuletdemon",
      name = "Fiend",
      slotType = "amulet",
      requiredLevel = 55,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["216"] = {
      kind = "amuletmoon",
      name = "Crescent",
      slotType = "amulet",
      requiredLevel = 54,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["228"] = {
      kind = "dragonarmor",
      name = "Dragon Armor",
      slotType = "armor",
      requiredLevel = 50,
      price = 40,
      flags = {},
      stackable = false,
      attributes = {
        defense = 44
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["229"] = {
      kind = "demonarmor",
      name = "Demon Armor",
      slotType = "armor",
      requiredLevel = 52,
      price = 140,
      flags = {},
      stackable = false,
      attributes = {
        defense = 46
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["230"] = {
      kind = "chestgreen",
      name = "Green Chest",
      requiredLevel = 56,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "The chest may contain a very precious item."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["231"] = {
      kind = "chestpurple",
      name = "Purple Chest",
      requiredLevel = 70,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "The chest may contain a very precious item."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["232"] = {
      kind = "chestred",
      name = "Red Chest",
      requiredLevel = 60,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "The chest may contain a very precious item."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["233"] = {
      kind = "amuletstar",
      name = "North Star",
      slotType = "amulet",
      requiredLevel = 58,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["240"] = {
      kind = "stonedragon",
      name = "Dragon Stone",
      requiredLevel = 60,
      price = 10000,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Blessed by the fire of the dragon, safely upgrade any item to +5"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["241"] = {
      kind = "stonehero",
      name = "Hero Emblem",
      requiredLevel = 65,
      price = 25000,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "You've crushed your enemies, saw them driven before you, and heard the lamentation of their women.<br/>Safely upgrade any item to +6"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["242"] = {
      kind = "mysticalarmor",
      name = "Mystical Armor",
      slotType = "armor",
      requiredLevel = 54,
      price = 85,
      flags = {},
      stackable = false,
      attributes = {
        defense = 48
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["244"] = {
      kind = "hellhammer",
      name = "Hell Hammer",
      slotType = "weapon",
      requiredLevel = 60,
      flags = {},
      stackable = false,
      attributes = {
        attack = 68
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["245"] = {
      kind = "chalice",
      name = "Golden Chalice",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "Return the Golden Chalice, a one-of-a-kind artifact, to its rightful place."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["249"] = {
      kind = "soulstone",
      name = "Soul Stone",
      flags = {
        "quest"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "This mysterious gem holds the soul of a hundred warriors."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["252"] = {
      kind = "immortalarmor",
      name = "Immortal Armor",
      slotType = "armor",
      requiredLevel = 58,
      price = 250,
      flags = {},
      stackable = false,
      attributes = {
        defense = 54
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["254"] = {
      kind = "tombdeathangel",
      name = "Death Angel Tomb",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["255"] = {
      kind = "tombangel",
      name = "Angel Tomb",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["256"] = {
      kind = "tombcross",
      name = "Tomb Cross",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["257"] = {
      kind = "tombskull",
      name = "Tomb Skull",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["269"] = {
      kind = "amuletskull",
      name = "White Death",
      slotType = "amulet",
      requiredLevel = 58,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["270"] = {
      kind = "amuletdragon",
      name = "Dragon Eye",
      slotType = "amulet",
      requiredLevel = 56,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["273"] = {
      kind = "nft",
      name = "Stone NFT",
      flags = {
        "quest",
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "An exceptional Non-Fungible Token artifact, return it to Alkor to get a reward."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["274"] = {
      kind = "wing",
      name = "Dragon Wing",
      flags = {
        "quest",
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "The remnants of a dragon's wing, return it to Olaf to get a reward."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["285"] = {
      kind = "crystal",
      name = "Crystal",
      flags = {
        "quest",
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "An ancient and powerful crystal, return it to Viktor to get a reward."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["286"] = {
      kind = "powderblack",
      name = "Soul Powder",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "A special kind of powder."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["287"] = {
      kind = "powderblue",
      name = "Illusion Powder",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "A special kind of powder."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["288"] = {
      kind = "powdergold",
      name = "BTC maxi Powder",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "A special kind of powder."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["289"] = {
      kind = "powdergreen",
      name = "Poison Powder",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "A special kind of powder."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["290"] = {
      kind = "powderred",
      name = "Blood Powder",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "A special kind of powder."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["291"] = {
      kind = "powderquantum",
      name = "Quantum Powder",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "The ultimate powder that powers the Gateway."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["301"] = {
      kind = "gatewayfx",
      name = "Gateway Effect",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["302"] = {
      kind = "gate",
      name = "Gate",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["304"] = {
      kind = "paladinarmor",
      name = "Paladin Armor",
      slotType = "armor",
      requiredLevel = 58,
      price = 250,
      flags = {},
      stackable = false,
      attributes = {
        defense = 54
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["305"] = {
      kind = "demonaxe",
      name = "Demon Axe",
      slotType = "weapon",
      requiredLevel = 60,
      price = 150,
      flags = {},
      stackable = false,
      attributes = {
        attack = 64
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["306"] = {
      kind = "paladinaxe",
      name = "Paladin Axe",
      slotType = "weapon",
      requiredLevel = 60,
      price = 250,
      flags = {},
      stackable = false,
      attributes = {
        attack = 66
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["307"] = {
      kind = "immortalsword",
      name = "Immortal Sword",
      slotType = "weapon",
      requiredLevel = 60,
      price = 250,
      flags = {},
      stackable = false,
      attributes = {
        attack = 66
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["309"] = {
      kind = "scrolltransmuteblessed",
      name = "Blessed transmute scroll",
      requiredLevel = 60,
      price = 5000,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Transmute a ring or an amulet and generate new random stats or an item to have a chance of making it unique. The chances of transmuting stats is fixed while the chances of getting a unique varies. There is a 1% chance your item will be burned during the transmutation."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["310"] = {
      kind = "pickaxe",
      name = "Pickaxe",
      slotType = "weapon",
      requiredLevel = 52,
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        attack = 30,
        description = "This tool is used for digging."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["311"] = {
      kind = "moonarmor",
      name = "Moon Armor",
      slotType = "armor",
      requiredLevel = 54,
      price = 50,
      flags = {},
      stackable = false,
      attributes = {
        defense = 44
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["313"] = {
      kind = "nanocoin",
      name = "Nanocoin",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["314"] = {
      kind = "bananocoin",
      name = "Bananocoin",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["317"] = {
      kind = "barbronze",
      name = "Bronze Bar",
      price = 1000,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Common metal."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["318"] = {
      kind = "barsilver",
      name = "Silver Bar",
      price = 10000,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Rare metal."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["319"] = {
      kind = "bargold",
      name = "Gold Bar",
      price = 100000,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Precious metal."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["320"] = {
      kind = "amuleteye",
      name = "All-Seeing Eye",
      slotType = "amulet",
      requiredLevel = 58,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["321"] = {
      kind = "ringgreed",
      name = "Ring of Greed",
      slotType = "ring1",
      requiredLevel = 50,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["322"] = {
      kind = "amuletgreed",
      name = "Amulet of Greed",
      slotType = "amulet",
      requiredLevel = 50,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["323"] = {
      kind = "barplatinum",
      name = "Platinum Bar",
      price = 1000000,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Priceless metal."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["324"] = {
      kind = "mushrooms",
      name = "Mushrooms",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      attributes = {
        description = "Mushrooms have the power to distort reality and summon otherworldly creatures."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["325"] = {
      kind = "player-head",
      name = "Cloth Helm",
      slotType = "helmet",
      requiredLevel = 1,
      flags = {},
      stackable = false,
      attributes = {
        defense = 1
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["326"] = {
      kind = "helmleather",
      name = "Leather Helm",
      slotType = "helmet",
      requiredLevel = 1,
      price = 2,
      flags = {},
      stackable = false,
      attributes = {
        defense = 2
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["327"] = {
      kind = "helmmail",
      name = "Mail Helm",
      slotType = "helmet",
      requiredLevel = 2,
      price = 3,
      flags = {},
      stackable = false,
      attributes = {
        defense = 3
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["328"] = {
      kind = "helmplate",
      name = "Plate Helm",
      slotType = "helmet",
      requiredLevel = 4,
      price = 4,
      flags = {},
      stackable = false,
      attributes = {
        defense = 5
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["329"] = {
      kind = "helmred",
      name = "Red Helm",
      slotType = "helmet",
      requiredLevel = 6,
      price = 5,
      flags = {},
      stackable = false,
      attributes = {
        defense = 7
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["330"] = {
      kind = "helmgolden",
      name = "Golden Helm",
      slotType = "helmet",
      requiredLevel = 8,
      price = 6,
      flags = {},
      stackable = false,
      attributes = {
        defense = 10
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["331"] = {
      kind = "helmblue",
      name = "Frozen Helm",
      slotType = "helmet",
      requiredLevel = 16,
      price = 8,
      flags = {},
      stackable = false,
      attributes = {
        defense = 12
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["332"] = {
      kind = "helmhorned",
      name = "Horned Helm",
      slotType = "helmet",
      requiredLevel = 20,
      price = 9,
      flags = {},
      stackable = false,
      attributes = {
        defense = 14
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["333"] = {
      kind = "helmfrozen",
      name = "Sapphire Helm",
      slotType = "helmet",
      requiredLevel = 24,
      price = 10,
      flags = {},
      stackable = false,
      attributes = {
        defense = 16
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["334"] = {
      kind = "helmdiamond",
      name = "Diamond Helm",
      slotType = "helmet",
      requiredLevel = 34,
      price = 100,
      flags = {},
      stackable = false,
      attributes = {
        defense = 18
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["335"] = {
      kind = "helmemerald",
      name = "Emerald Helm",
      slotType = "helmet",
      requiredLevel = 46,
      price = 30,
      flags = {},
      stackable = false,
      attributes = {
        defense = 20
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["336"] = {
      kind = "helmexecutioner",
      name = "Executioner Helm",
      slotType = "helmet",
      requiredLevel = 48,
      price = 32,
      flags = {},
      stackable = false,
      attributes = {
        defense = 20
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["337"] = {
      kind = "helmtemplar",
      name = "Templar Helm",
      slotType = "helmet",
      requiredLevel = 48,
      price = 34,
      flags = {},
      stackable = false,
      attributes = {
        defense = 20
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["338"] = {
      kind = "helmdragon",
      name = "Dragon Helm",
      slotType = "helmet",
      requiredLevel = 48,
      price = 36,
      flags = {},
      stackable = false,
      attributes = {
        defense = 20
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["339"] = {
      kind = "helmmoon",
      name = "Moon Helm",
      slotType = "helmet",
      requiredLevel = 50,
      price = 42,
      flags = {},
      stackable = false,
      attributes = {
        defense = 20
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["340"] = {
      kind = "helmdemon",
      name = "Demon Helm",
      slotType = "helmet",
      requiredLevel = 50,
      price = 110,
      flags = {},
      stackable = false,
      attributes = {
        defense = 22
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["341"] = {
      kind = "helmmystical",
      name = "Mystical Helm",
      slotType = "helmet",
      requiredLevel = 52,
      price = 72,
      flags = {},
      stackable = false,
      attributes = {
        defense = 22
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["342"] = {
      kind = "helmimmortal",
      name = "Immortal Helm",
      slotType = "helmet",
      requiredLevel = 54,
      price = 98,
      flags = {},
      stackable = false,
      attributes = {
        defense = 26
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["343"] = {
      kind = "helmclown",
      name = "Clown Helm",
      slotType = "helmet",
      requiredLevel = 42,
      price = 450,
      flags = {},
      stackable = false,
      attributes = {
        defense = 20
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["344"] = {
      kind = "beltgoldwrap",
      name = "Goldwrap",
      slotType = "belt",
      requiredLevel = 42,
      price = 115,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["351"] = {
      kind = "helmpaladin",
      name = "Paladin Helm",
      slotType = "helmet",
      requiredLevel = 54,
      price = 98,
      flags = {},
      stackable = false,
      attributes = {
        defense = 26
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["352"] = {
      kind = "beltpaladin",
      name = "Paladin Belt",
      slotType = "belt",
      requiredLevel = 58,
      price = 115,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["353"] = {
      kind = "shieldpaladin",
      name = "Paladin Shield",
      slotType = "shield",
      requiredLevel = 56,
      price = 120,
      flags = {},
      stackable = false,
      attributes = {
        defense = 34
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["354"] = {
      kind = "shieldimmortal",
      name = "Immortal Shield",
      slotType = "shield",
      requiredLevel = 56,
      price = 120,
      flags = {},
      stackable = false,
      attributes = {
        defense = 34
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["355"] = {
      kind = "beltimmortal",
      name = "Immortal Belt",
      slotType = "belt",
      requiredLevel = 58,
      price = 115,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["356"] = {
      kind = "iou",
      name = "Iou",
      flags = {
        "unsplitable"
      },
      stackable = false,
      rarity = 3,
      attributes = {
        description = "Written acknowledgment of a debt.<br/>Talk to Janet Yellen to exchange it for :amount: gold."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["357"] = {
      kind = "petegg",
      name = "Pet Egg",
      flags = {},
      stackable = false,
      attributes = {
        description = "An egg of a dinosaur pet with colorful scales and a heart of loyalty, forming a strong bond with you as you explore the world together"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["358"] = {
      kind = "petdino",
      name = "Dinosaur Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["359"] = {
      kind = "pet_dino",
      name = "Pet Dino",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["360"] = {
      kind = "petbat",
      name = "Bat Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["361"] = {
      kind = "pet_bat",
      name = "Pet Bat",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["362"] = {
      kind = "petcat",
      name = "Cat Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["363"] = {
      kind = "pet_cat",
      name = "Pet Cat",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["364"] = {
      kind = "petdog",
      name = "Dog Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["365"] = {
      kind = "pet_dog",
      name = "Pet Dog",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["366"] = {
      kind = "petturtle",
      name = "Turtle Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["367"] = {
      kind = "pet_turtle",
      name = "Pet Turtle",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["368"] = {
      kind = "petaxolotl",
      name = "Axolotl Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["369"] = {
      kind = "pet_axolotl",
      name = "Pet Axolotl",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["370"] = {
      kind = "petfox",
      name = "Fox Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["371"] = {
      kind = "pet_fox",
      name = "Pet Fox",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["372"] = {
      kind = "petmouse",
      name = "Mouse Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["373"] = {
      kind = "pet_mouse",
      name = "Pet Mouse",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["374"] = {
      kind = "pethedgehog",
      name = "Hedgehog Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["375"] = {
      kind = "pet_hedgehog",
      name = "Pet Hedgehog",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["376"] = {
      kind = "stonesocketblessed",
      name = "Blesssed Socket Stone",
      requiredLevel = 61,
      price = 17500,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Creates a random number of sockets in a non-socketed item.  If all sockets are empty, you can re-roll sockets up to 6 on unique items or 5 for normal items.<br/><br/>If the item already has sockets, the stone will attempt to remove the last item from its socket. There is 1% chance for the extracting item to be burned."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["377"] = {
      kind = "maul",
      name = "Maul",
      slotType = "weapon",
      requiredLevel = 62,
      flags = {},
      stackable = false,
      attributes = {
        attack = 73
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["378"] = {
      kind = "wizardsword",
      name = "Wizard sword",
      slotType = "weapon",
      requiredLevel = 62,
      flags = {},
      stackable = false,
      attributes = {
        attack = 71
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["379"] = {
      kind = "scrolltransmutepet",
      name = "Pet transmute scroll",
      requiredLevel = 60,
      price = 4000,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Re-roll a Pet type & skin, 99% chance of succeeding"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["380"] = {
      kind = "scrollupgradeelementmagic",
      name = "Blessed Magic Element upgrade scroll",
      requiredLevel = 44,
      price = 2500,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Enchant a high or legendary weapon with magic spell offensive skill, 99% success"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["381"] = {
      kind = "scrollupgradeelementflame",
      name = "Blessed Flame Element upgrade scroll",
      requiredLevel = 44,
      price = 2500,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Enchant a high or legendary  weapon with flame spell offensive skill, 99% success"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["382"] = {
      kind = "scrollupgradeelementlightning",
      name = "Lightning Element upgrade scroll",
      requiredLevel = 44,
      price = 2500,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Enchant a high or a legendary weapon with lightning spell offensive skill, 99% success"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["383"] = {
      kind = "scrollupgradeelementcold",
      name = "Blessed Cold Element upgrade scroll",
      requiredLevel = 44,
      price = 2500,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Enchant a high or a legendary weapon with cold spell offensive skill, 99% success"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["384"] = {
      kind = "scrollupgradeelementpoison",
      name = "Blessed Poison Element upgrade scroll",
      requiredLevel = 44,
      price = 2500,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Enchant a high or a legendary weapon with poison spell offensive skill, 99% success"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["385"] = {
      kind = "scrollupgradeskillrandom",
      name = "Blessed Random Skill upgrade scroll",
      requiredLevel = 44,
      price = 5000,
      flags = {
        "scroll"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Enchant a  a high or legendary  weapon or shield with a random ability (current ability will be changed or it has a chance to stay unchanged), 99% success"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["386"] = {
      kind = "petduck",
      name = "Duck Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["387"] = {
      kind = "pet_duck",
      name = "Pet Duck",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["388"] = {
      kind = "helmpumkin",
      name = "Special Event Pumpkin Helm",
      slotType = "helmet",
      requiredLevel = 42,
      price = 1150,
      flags = {},
      stackable = false,
      attributes = {
        defense = 20
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["389"] = {
      kind = "pet_dragon",
      name = "Pet Dragon",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["390"] = {
      kind = "petdragon",
      name = "Dragon Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["392"] = {
      kind = "pet_deer",
      name = "Pet Deer",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["393"] = {
      kind = "chestdead",
      name = "Dead Chest",
      requiredLevel = 72,
      flags = {},
      stackable = true,
      maxStack = 100,
      source = "packages/common/game/itemsData.ts"
    },
    ["394"] = {
      kind = "ringpumkin",
      name = "Special Event Pumpkin Ring",
      slotType = "ring1",
      requiredLevel = 42,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["395"] = {
      kind = "expansion2voucher",
      name = "Lost Temple Expansion Voucher",
      requiredLevel = 50,
      flags = {
        "consumable"
      },
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "Lost Temple expansion Voucher when consumed in the Anvil the Lost Temple will unlock if you don't already have it."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["396"] = {
      kind = "stoneteleport",
      name = "Teleport Stone",
      requiredLevel = 45,
      price = 200,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "This stone allows you to teleport to any party member."
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["397"] = {
      kind = "panelskeletonkey",
      name = "Skeleton Key Panel",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["398"] = {
      kind = "ringbadomen",
      name = "Bad Omen Ring",
      slotType = "ring1",
      requiredLevel = 64,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["399"] = {
      kind = "ringbloodband",
      name = "Blood Band Ring",
      slotType = "ring1",
      requiredLevel = 64,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["400"] = {
      kind = "petcollar",
      name = "Pet Collar",
      flags = {},
      stackable = false,
      attributes = {
        description = "+1: Name your Pet"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["401"] = {
      kind = "mysticaldagger",
      name = "Mystical Dagger",
      slotType = "weapon",
      requiredLevel = 56,
      price = 85,
      flags = {},
      stackable = false,
      attributes = {
        attack = 58
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["402"] = {
      kind = "moonhachet",
      name = "Moon Hatchet",
      slotType = "weapon",
      requiredLevel = 59,
      price = 50,
      flags = {},
      stackable = false,
      attributes = {
        attack = 58
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["403"] = {
      kind = "moonmaul",
      name = "Moon Maul",
      slotType = "weapon",
      requiredLevel = 59,
      price = 50,
      flags = {},
      stackable = false,
      attributes = {
        attack = 62
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["404"] = {
      kind = "demonsickle",
      name = "Demon Sickle",
      slotType = "weapon",
      requiredLevel = 60,
      price = 150,
      flags = {},
      stackable = false,
      attributes = {
        attack = 62
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["406"] = {
      kind = "pet_reindeer",
      name = "Pet Reindeer",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["407"] = {
      kind = "pethellhound",
      name = "Hellhound Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["408"] = {
      kind = "pet_hellhound",
      name = "Pet Hellhound",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["409"] = {
      kind = "petdeer",
      name = "Deer Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["410"] = {
      kind = "demonmaul",
      name = "Demon Maul",
      slotType = "weapon",
      requiredLevel = 61,
      price = 150,
      flags = {},
      stackable = false,
      attributes = {
        attack = 66
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["411"] = {
      kind = "christmaspresent",
      name = "Christmas Present",
      requiredLevel = 40,
      flags = {},
      stackable = true,
      maxStack = 100,
      attributes = {
        description = "The present contains a special christmas event set items"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["412"] = {
      kind = "christmassword",
      name = "Christmas Sword",
      slotType = "weapon",
      requiredLevel = 44,
      price = 40,
      flags = {},
      stackable = false,
      attributes = {
        attack = 60
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["413"] = {
      kind = "christmashachet",
      name = "Christmas Hatchet",
      slotType = "weapon",
      requiredLevel = 59,
      price = 40,
      flags = {},
      stackable = false,
      attributes = {
        attack = 58
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["414"] = {
      kind = "shieldchristmas",
      name = "Christmas Shield",
      slotType = "shield",
      requiredLevel = 52,
      flags = {},
      stackable = false,
      attributes = {
        defense = 30
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["415"] = {
      kind = "beltchristmas",
      name = "Christmas Belt",
      slotType = "belt",
      requiredLevel = 54,
      price = 42,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["416"] = {
      kind = "amuletchristmas",
      name = "Yule",
      slotType = "amulet",
      requiredLevel = 54,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["417"] = {
      kind = "christmasmaul",
      name = "christmas Maul",
      slotType = "weapon",
      requiredLevel = 59,
      price = 40,
      flags = {},
      stackable = false,
      attributes = {
        attack = 62
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["418"] = {
      kind = "petreindeer",
      name = "ReinDeer Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["419"] = {
      kind = "petmonkey",
      name = "Monkey Pet",
      requiredLevel = 10,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["420"] = {
      kind = "helmchristmas",
      name = "Christmas Helm",
      slotType = "helmet",
      requiredLevel = 50,
      price = 42,
      flags = {},
      stackable = false,
      attributes = {
        defense = 20
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["421"] = {
      kind = "christmasarmor",
      name = "Christmas Armor",
      slotType = "armor",
      requiredLevel = 54,
      flags = {},
      stackable = false,
      attributes = {
        defense = 44
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["422"] = {
      kind = "pet_monkey",
      name = "Pet Monkey",
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["423"] = {
      kind = "amuletimmortal",
      name = "Necklace of the Timeless Soul",
      slotType = "amulet",
      requiredLevel = 65,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["424"] = {
      kind = "ringimmortal",
      name = "Eternity Band of the Ancients",
      slotType = "ring1",
      requiredLevel = 65,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["425"] = {
      kind = "ringpaladin",
      name = "Holy Protector's Seal",
      slotType = "ring1",
      requiredLevel = 65,
      flags = {},
      stackable = false,
      customAttributes = {
        allowedSlots = {
          3,
          4
        }
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["426"] = {
      kind = "amuletpaladin",
      name = "Celestial Ward Amulet",
      slotType = "amulet",
      requiredLevel = 65,
      flags = {},
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["427"] = {
      kind = "immortalaxe",
      name = "Immortarion, the Timeless Cleaver",
      slotType = "weapon",
      requiredLevel = 60,
      price = 250,
      flags = {},
      stackable = false,
      attributes = {
        attack = 66
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["428"] = {
      kind = "immortaldagger",
      name = "Immortal Dagger",
      slotType = "weapon",
      requiredLevel = 60,
      price = 250,
      flags = {},
      stackable = false,
      attributes = {
        attack = 66
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["1000"] = {
      kind = "jewelskullcommon",
      name = "Skull Jewel",
      requiredLevel = 20,
      price = 10,
      flags = {},
      stackable = false,
      rarity = 0,
      attributes = {
        description = "Can be inserted in a socket"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["1001"] = {
      kind = "jewelskulluncommon",
      name = "Skull Jewel",
      requiredLevel = 51,
      price = 25,
      flags = {},
      stackable = false,
      rarity = 1,
      attributes = {
        description = "Can be inserted in a socket"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["1002"] = {
      kind = "jewelskullrare",
      name = "Skull Jewel",
      requiredLevel = 51,
      price = 100,
      flags = {},
      stackable = false,
      rarity = 2,
      attributes = {
        description = "Can be inserted in a socket"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["1003"] = {
      kind = "jewelskullepic",
      name = "Skull Jewel",
      requiredLevel = 51,
      price = 250,
      flags = {},
      stackable = false,
      rarity = 3,
      attributes = {
        description = "Can be inserted in a socket"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["1004"] = {
      kind = "jewelskulllegendary",
      name = "Skull Jewel",
      requiredLevel = 51,
      price = 1000,
      flags = {},
      stackable = false,
      rarity = 4,
      attributes = {
        description = "Can be inserted in a socket"
      },
      source = "packages/common/game/itemsData.ts"
    },
    ["2000"] = {
      kind = "stash",
      name = "Stash",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["2001"] = {
      kind = "anvil",
      name = "Anvil",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11482"] = {
      kind = "waypoint",
      name = "Waypoint",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11484"] = {
      kind = "portalcow",
      name = "Cow Portal",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11485"] = {
      kind = "portalminotaur",
      name = "Minotaur Portal",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11487"] = {
      kind = "magicstone",
      name = "Magic Stone",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11488"] = {
      kind = "blueflame",
      name = "Blue Flame",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11489"] = {
      kind = "portalstone",
      name = "Stone Portal",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11490"] = {
      kind = "portalgateway",
      name = "Gateway Portal",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11491"] = {
      kind = "altarchalice",
      name = "Chalice Altar",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11492"] = {
      kind = "altarsoulstone",
      name = "Soulstone Altar",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11493"] = {
      kind = "secretstairs",
      name = "Secret Stairs",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11494"] = {
      kind = "secretstairsup",
      name = "Secret Stairs Up",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11495"] = {
      kind = "lever",
      name = "Lever",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11496"] = {
      kind = "lever2",
      name = "Lever",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11497"] = {
      kind = "grimoire",
      name = "Grimoire",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11498"] = {
      kind = "secretstairs2",
      name = "Secret Stairs",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11499"] = {
      kind = "fossil",
      name = "Fossil",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11500"] = {
      kind = "hands",
      name = "Hands",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11501"] = {
      kind = "doordeathangel",
      name = "Death Angel Door",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11502"] = {
      kind = "obelisk",
      name = "Obelisk",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11503"] = {
      kind = "lever3",
      name = "Lever",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11504"] = {
      kind = "memorial",
      name = "Memorial",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["11505"] = {
      kind = "teleporttrigger",
      name = "Teleport Trigger",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    },
    ["90018"] = {
      kind = "tree",
      name = "Tree",
      flags = {
        "untradable",
        "unique"
      },
      stackable = false,
      source = "packages/common/game/itemsData.ts"
    }
  },
  byKind = {
    backpack = 1,
    firefox = 20,
    ["player-body"] = 21,
    leatherarmor = 22,
    mailarmor = 23,
    platearmor = 24,
    redarmor = 25,
    goldenarmor = 26,
    flask = 35,
    burger = 36,
    chest = 37,
    firefoxpotion = 38,
    cake = 39,
    dagger = 60,
    sword = 61,
    morningstar = 62,
    axe = 63,
    bluesword = 64,
    redsword = 65,
    goldensword = 66,
    nanopotion = 67,
    gemruby = 68,
    gememerald = 69,
    gemamethyst = 70,
    gemtopaz = 71,
    scrollupgradelow = 74,
    scrollupgrademedium = 75,
    scrollupgradehigh = 76,
    blueaxe = 77,
    frozenarmor = 78,
    gemsapphire = 79,
    ringbronze = 80,
    ringsilver = 81,
    ringgold = 82,
    hornedarmor = 83,
    beltleather = 85,
    beltplated = 86,
    bluearmor = 87,
    beltfrozen = 91,
    gold = 92,
    skeletonkey = 94,
    raiblockstl = 95,
    raiblockstr = 96,
    raiblocksbl = 97,
    raiblocksbr = 98,
    frozensword = 100,
    bluemorningstar = 107,
    rejuvenationpotion = 110,
    poisonpotion = 111,
    amuletsilver = 112,
    amuletgold = 113,
    ringnecromancer = 115,
    amuletcow = 116,
    ringraistone = 117,
    scrollupgradeblessed = 118,
    diamondsword = 121,
    wirtleg = 122,
    skeletonkingcage = 123,
    necromancerheart = 124,
    ringfountain = 126,
    diamondarmor = 127,
    emeraldarmor = 128,
    beltdiamond = 129,
    cape = 130,
    capehigh = 131,
    ringminotaur = 132,
    minotauraxe = 133,
    beltminotaur = 134,
    chestblue = 136,
    cowkinghorn = 137,
    amuletfrozen = 138,
    bananopotion = 139,
    templararmor = 140,
    belthorned = 141,
    scrolltransmute = 142,
    shieldwood = 143,
    shieldiron = 144,
    shieldplate = 145,
    shieldred = 146,
    shieldgolden = 147,
    shieldblue = 148,
    shieldhorned = 149,
    shieldfrozen = 150,
    shielddiamond = 151,
    emeraldsword = 152,
    shieldtemplar = 153,
    executionersword = 154,
    templarsword = 155,
    dragonsword = 156,
    moonsword = 157,
    mysticalsword = 158,
    spikeglaive = 159,
    eclypsedagger = 160,
    ["rune-sat"] = 161,
    ["rune-al"] = 162,
    ["rune-bul"] = 163,
    ["rune-nan"] = 164,
    ["rune-mir"] = 165,
    ["rune-gel"] = 166,
    ["rune-do"] = 167,
    ["rune-ban"] = 168,
    ["rune-vie"] = 169,
    ["rune-um"] = 170,
    ["rune-hex"] = 171,
    ["rune-zal"] = 172,
    ["rune-sol"] = 173,
    ["rune-eth"] = 174,
    ["rune-btc"] = 175,
    ["rune-vax"] = 176,
    ["rune-por"] = 177,
    ["rune-las"] = 178,
    ["rune-dur"] = 179,
    ["rune-fal"] = 180,
    ["rune-kul"] = 181,
    ["rune-mer"] = 182,
    ["rune-qua"] = 183,
    ["rune-gul"] = 184,
    ["rune-ber"] = 185,
    ["rune-cham"] = 186,
    ["rune-tor"] = 187,
    ["rune-xno"] = 188,
    ["rune-jah"] = 189,
    ["rune-shi"] = 190,
    ["rune-vod"] = 191,
    stonesocket = 192,
    ringbalrog = 194,
    shieldexecutioner = 195,
    shieldmystical = 196,
    shielddragon = 197,
    shielddemon = 198,
    shieldemerald = 199,
    scrollupgradelegendary = 200,
    beltemerald = 201,
    beltmystical = 202,
    belttemplar = 203,
    beltdemon = 204,
    beltmoon = 205,
    scrollupgradesacred = 206,
    beltexecutioner = 207,
    shieldmoon = 208,
    ringplatinum = 209,
    ringconqueror = 210,
    ringheaven = 211,
    amuletplatinum = 212,
    ringwizard = 213,
    ringmystical = 214,
    amuletdemon = 215,
    amuletmoon = 216,
    dragonarmor = 228,
    demonarmor = 229,
    chestgreen = 230,
    chestpurple = 231,
    chestred = 232,
    amuletstar = 233,
    stonedragon = 240,
    stonehero = 241,
    mysticalarmor = 242,
    hellhammer = 244,
    chalice = 245,
    soulstone = 249,
    immortalarmor = 252,
    tombdeathangel = 254,
    tombangel = 255,
    tombcross = 256,
    tombskull = 257,
    amuletskull = 269,
    amuletdragon = 270,
    nft = 273,
    wing = 274,
    crystal = 285,
    powderblack = 286,
    powderblue = 287,
    powdergold = 288,
    powdergreen = 289,
    powderred = 290,
    powderquantum = 291,
    gatewayfx = 301,
    gate = 302,
    paladinarmor = 304,
    demonaxe = 305,
    paladinaxe = 306,
    immortalsword = 307,
    scrolltransmuteblessed = 309,
    pickaxe = 310,
    moonarmor = 311,
    nanocoin = 313,
    bananocoin = 314,
    barbronze = 317,
    barsilver = 318,
    bargold = 319,
    amuleteye = 320,
    ringgreed = 321,
    amuletgreed = 322,
    barplatinum = 323,
    mushrooms = 324,
    ["player-head"] = 325,
    helmleather = 326,
    helmmail = 327,
    helmplate = 328,
    helmred = 329,
    helmgolden = 330,
    helmblue = 331,
    helmhorned = 332,
    helmfrozen = 333,
    helmdiamond = 334,
    helmemerald = 335,
    helmexecutioner = 336,
    helmtemplar = 337,
    helmdragon = 338,
    helmmoon = 339,
    helmdemon = 340,
    helmmystical = 341,
    helmimmortal = 342,
    helmclown = 343,
    beltgoldwrap = 344,
    helmpaladin = 351,
    beltpaladin = 352,
    shieldpaladin = 353,
    shieldimmortal = 354,
    beltimmortal = 355,
    iou = 356,
    petegg = 357,
    petdino = 358,
    pet_dino = 359,
    petbat = 360,
    pet_bat = 361,
    petcat = 362,
    pet_cat = 363,
    petdog = 364,
    pet_dog = 365,
    petturtle = 366,
    pet_turtle = 367,
    petaxolotl = 368,
    pet_axolotl = 369,
    petfox = 370,
    pet_fox = 371,
    petmouse = 372,
    pet_mouse = 373,
    pethedgehog = 374,
    pet_hedgehog = 375,
    stonesocketblessed = 376,
    maul = 377,
    wizardsword = 378,
    scrolltransmutepet = 379,
    scrollupgradeelementmagic = 380,
    scrollupgradeelementflame = 381,
    scrollupgradeelementlightning = 382,
    scrollupgradeelementcold = 383,
    scrollupgradeelementpoison = 384,
    scrollupgradeskillrandom = 385,
    petduck = 386,
    pet_duck = 387,
    helmpumkin = 388,
    pet_dragon = 389,
    petdragon = 390,
    pet_deer = 392,
    chestdead = 393,
    ringpumkin = 394,
    expansion2voucher = 395,
    stoneteleport = 396,
    panelskeletonkey = 397,
    ringbadomen = 398,
    ringbloodband = 399,
    petcollar = 400,
    mysticaldagger = 401,
    moonhachet = 402,
    moonmaul = 403,
    demonsickle = 404,
    pet_reindeer = 406,
    pethellhound = 407,
    pet_hellhound = 408,
    petdeer = 409,
    demonmaul = 410,
    christmaspresent = 411,
    christmassword = 412,
    christmashachet = 413,
    shieldchristmas = 414,
    beltchristmas = 415,
    amuletchristmas = 416,
    christmasmaul = 417,
    petreindeer = 418,
    petmonkey = 419,
    helmchristmas = 420,
    christmasarmor = 421,
    pet_monkey = 422,
    amuletimmortal = 423,
    ringimmortal = 424,
    ringpaladin = 425,
    amuletpaladin = 426,
    immortalaxe = 427,
    immortaldagger = 428,
    jewelskullcommon = 1000,
    jewelskulluncommon = 1001,
    jewelskullrare = 1002,
    jewelskullepic = 1003,
    jewelskulllegendary = 1004,
    stash = 2000,
    anvil = 2001,
    waypoint = 11482,
    portalcow = 11484,
    portalminotaur = 11485,
    magicstone = 11487,
    blueflame = 11488,
    portalstone = 11489,
    portalgateway = 11490,
    altarchalice = 11491,
    altarsoulstone = 11492,
    secretstairs = 11493,
    secretstairsup = 11494,
    lever = 11495,
    lever2 = 11496,
    grimoire = 11497,
    secretstairs2 = 11498,
    fossil = 11499,
    hands = 11500,
    doordeathangel = 11501,
    obelisk = 11502,
    lever3 = 11503,
    memorial = 11504,
    teleporttrigger = 11505,
    tree = 90018
  },
}
