-- Generated by tools/export_nbq_content.mjs. Do not edit by hand.
NBQMonsterRegistry = {
  byKind = {
    bat = {
      name = "Bat",
      race = "blood",
      level = 3,
      hasScript = false,
      source = "data/monster/monsters/bat.ts",
      spells = {
        {
          id = "monster-bat-life-drain",
          source = "data/spells/monster/batLifeDrain.ts",
          targetMode = "target",
          combatType = 6
        },
        {
          id = "monster-bat-blood-heal",
          source = "data/spells/monster/batBloodHeal.ts",
          targetMode = "self",
          combatType = 7
        }
      }
    },
    deathangel = {
      name = "Azrael",
      race = "undead",
      level = 80,
      damageModifier = {
        magic = 100,
        flame = 100,
        lightning = 100,
        cold = 100,
        poison = 100
      },
      enchantments = {
        "spectral",
        "curse-resistance"
      },
      spawnBehavior = {
        resistances = {
          randomCount = 3,
          randomBossRange = {
            min = 20,
            max = 80,
            step = 10,
            skipFirst = true
          }
        },
        enchantments = {
          extraRandomCount = 2
        }
      },
      hasScript = true,
      source = "data/monster/monsters/bosses/azrael.ts",
      spells = {}
    },
    butcher = {
      name = "Gorefiend the Butcher",
      race = "blood",
      level = 96,
      damageModifier = {
        magic = 50,
        flame = 100,
        lightning = 70,
        cold = 25,
        poison = 40
      },
      enchantments = {
        "physical"
      },
      spawnBehavior = {
        resistances = {
          randomCount = 3
        },
        enchantments = {
          extraRandomCount = 2
        }
      },
      hasScript = true,
      source = "data/monster/monsters/bosses/butcher.ts",
      spells = {}
    },
    cowking = {
      name = "Cow King",
      race = "blood",
      level = 66,
      damageModifier = {
        lightning = 100,
        flame = 20
      },
      enchantments = {
        "lightning",
        "curse-resistance"
      },
      hasScript = false,
      source = "data/monster/monsters/bosses/cow_king.ts",
      spells = {}
    },
    minotaur = {
      name = "Minotaur",
      race = "blood",
      level = 72,
      damageModifier = {
        magic = 80,
        flame = 100,
        lightning = 100
      },
      enchantments = {
        "cold"
      },
      hasScript = true,
      source = "data/monster/monsters/bosses/minotaur.ts",
      spells = {}
    },
    necromancer = {
      name = "Necromancer",
      race = "undead",
      level = 58,
      damageModifier = {
        magic = 50,
        flame = 50,
        lightning = 50,
        cold = 100
      },
      spawnBehavior = {
        resistances = {
          randomCount = 2
        },
        enchantments = {
          fallbackRandomCount = 1
        }
      },
      hasScript = true,
      source = "data/monster/monsters/bosses/necromancer.ts",
      spells = {}
    },
    shaman = {
      name = "Zul'Gurak",
      race = "blood",
      level = 87,
      damageModifier = {
        magic = 60,
        flame = 60,
        lightning = 30,
        cold = 30,
        poison = 30
      },
      spawnBehavior = {
        element = {
          mode = "random_pool",
          options = {
            "magic",
            "flame",
            "lightning",
            "cold",
            "poison"
          }
        },
        resistances = {
          randomCount = 3
        },
        enchantments = {
          extraRandomCount = 2
        }
      },
      hasScript = false,
      source = "data/monster/monsters/bosses/shaman.ts",
      spells = {}
    },
    skeletoncommander = {
      name = "Skeleton Commander",
      race = "blood",
      level = 51,
      hasScript = false,
      source = "data/monster/monsters/bosses/skeleton_commander.ts",
      spells = {}
    },
    boss = {
      name = "Skeleton King",
      race = "undead",
      level = 32,
      damageModifier = {
        magic = 50,
        flame = 50
      },
      hasScript = false,
      source = "data/monster/monsters/bosses/skeleton_king.ts",
      spells = {}
    },
    skeletontemplar = {
      name = "Skeleton Templar",
      race = "blood",
      level = 83,
      damageModifier = {
        magic = 80,
        flame = 80,
        lightning = 80,
        cold = 80,
        poison = 100
      },
      enchantments = {
        "poison",
        "cold"
      },
      hasScript = false,
      source = "data/monster/monsters/bosses/skeleton_templar.ts",
      spells = {}
    },
    worm = {
      name = "Shai-Hulud",
      race = "blood",
      level = 90,
      damageModifier = {
        magic = 70,
        flame = 55,
        lightning = 60,
        cold = 60,
        poison = 40
      },
      enchantments = {
        "physical",
        "curse-health"
      },
      spawnBehavior = {
        resistances = {
          randomCount = 3
        },
        enchantments = {
          extraRandomCount = 2
        }
      },
      hasScript = false,
      source = "data/monster/monsters/bosses/worm.ts",
      spells = {}
    },
    cow = {
      name = "Cow",
      race = "blood",
      level = 61,
      spawnBehavior = {
        resistances = {
          randomCount = 0
        },
        enchantments = {
          miniBossChance = 40
        }
      },
      hasScript = false,
      source = "data/monster/monsters/cow.ts",
      spells = {}
    },
    crab = {
      name = "Crab",
      race = "blood",
      level = 1,
      hasScript = false,
      source = "data/monster/monsters/crab.ts",
      spells = {}
    },
    snake4 = {
      name = "Damned Snake",
      race = "blood",
      level = 76,
      damageModifier = {
        flame = 100
      },
      enchantments = {
        "flame"
      },
      hasScript = false,
      source = "data/monster/monsters/damned_snake.ts",
      spells = {}
    },
    deathbringer = {
      name = "Death Bringer",
      race = "blood",
      level = 93,
      damageModifier = {
        magic = 100,
        flame = 100,
        lightning = 100,
        cold = 100,
        poison = 100
      },
      enchantments = {
        "spectral",
        "curse-health"
      },
      spawnBehavior = {
        element = {
          mode = "fixed",
          value = "flame"
        },
        resistances = {
          randomCount = 3
        },
        enchantments = {
          extraRandomCount = 2
        }
      },
      hasScript = false,
      source = "data/monster/monsters/deathbringer.ts",
      spells = {}
    },
    deathknight = {
      name = "Death Knight",
      race = "blood",
      level = 26,
      hasScript = false,
      source = "data/monster/monsters/deathknight.ts",
      spells = {}
    },
    eye = {
      name = "Eye",
      race = "blood",
      level = 17,
      hasScript = false,
      source = "data/monster/monsters/eye.ts",
      spells = {}
    },
    ghost = {
      name = "Ghost",
      race = "blood",
      level = 83,
      damageModifier = {
        magic = 60,
        flame = 20,
        lightning = 30,
        cold = 30
      },
      hasScript = false,
      source = "data/monster/monsters/ghost.ts",
      spells = {}
    },
    goblin = {
      name = "Goblin",
      race = "blood",
      level = 6,
      hasScript = false,
      source = "data/monster/monsters/goblin.ts",
      spells = {}
    },
    golem = {
      name = "Golem",
      race = "blood",
      level = 76,
      enchantments = {
        "physical",
        "stoneskin"
      },
      hasScript = false,
      source = "data/monster/monsters/golem.ts",
      spells = {}
    },
    kobold = {
      name = "Kobold",
      race = "blood",
      level = 79,
      damageModifier = {
        magic = 40,
        flame = 60,
        lightning = 80,
        cold = 20
      },
      hasScript = false,
      source = "data/monster/monsters/kobold.ts",
      spells = {}
    },
    mage = {
      name = "Mage",
      race = "blood",
      level = 94,
      damageModifier = {
        magic = 50,
        flame = 50,
        lightning = 50,
        cold = 50,
        poison = 50
      },
      spawnBehavior = {
        element = {
          mode = "random"
        },
        resistances = {
          randomCount = 2
        },
        appearance = {
          rules = {
            {
              kind = "mage-cold",
              lookTypeId = 20,
              when = {
                element = "cold"
              }
            },
            {
              kind = "mage-flame",
              lookTypeId = 21,
              when = {
                element = "flame"
              }
            },
            {
              kind = "mage-lightning",
              lookTypeId = 22,
              when = {
                element = "lightning"
              }
            },
            {
              kind = "mage-magic",
              lookTypeId = 23,
              when = {
                element = "magic"
              }
            },
            {
              kind = "mage-poison",
              lookTypeId = 24,
              when = {
                element = "poison"
              }
            }
          }
        }
      },
      hasScript = false,
      source = "data/monster/monsters/mage.ts",
      spells = {
        {
          id = "monster-mage-arcane-bolt",
          source = "data/spells/monster/mageArcaneBolt.ts",
          targetMode = "target",
          combatType = 8
        },
        {
          id = "monster-mage-fire-burst",
          source = "data/spells/monster/mageFireBurst.ts",
          targetMode = "target",
          combatType = 2,
          area = {
            {
              1,
              1,
              1
            },
            {
              1,
              3,
              1
            },
            {
              1,
              1,
              1
            }
          }
        }
      }
    },
    oculothorax = {
      name = "Oculothorax",
      race = "blood",
      level = 79,
      damageModifier = {
        magic = 40,
        flame = 100,
        lightning = 80,
        cold = 40
      },
      hasScript = false,
      source = "data/monster/monsters/oculothorax.ts",
      spells = {}
    },
    ogre = {
      name = "Ogre",
      race = "blood",
      level = 12,
      hasScript = false,
      source = "data/monster/monsters/ogre.ts",
      spells = {}
    },
    rat3 = {
      name = "Poison Rat",
      race = "venom",
      level = 63,
      damageModifier = {
        poison = 100
      },
      enchantments = {
        "poison"
      },
      hasScript = false,
      source = "data/monster/monsters/poison_rat.ts",
      spells = {}
    },
    rat = {
      name = "Rat",
      race = "blood",
      level = 2,
      hasScript = false,
      source = "data/monster/monsters/rat.ts",
      spells = {
        {
          id = "monster-rat-bite",
          source = "data/spells/monster/ratBite.ts",
          targetMode = "target",
          combatType = 1
        }
      }
    },
    snake2 = {
      name = "Sea Snake",
      race = "ice",
      level = 62,
      damageModifier = {
        cold = 100
      },
      hasScript = false,
      source = "data/monster/monsters/sea_snake.ts",
      spells = {
        {
          id = "monster-sea-snake-frost-spit",
          source = "data/spells/monster/seaSnakeFrostSpit.ts",
          targetMode = "target",
          combatType = 3,
          condition = {
            type = "freezing",
            duration = 4000,
            speedChange = -100
          },
          unsupportedConditionSpeedChange = -100
        }
      }
    },
    skeletonarcher = {
      name = "Skeleton Archer",
      race = "blood",
      level = 84,
      damageModifier = {
        magic = 40,
        flame = 45,
        lightning = 50,
        cold = 55,
        poison = 40
      },
      spawnBehavior = {
        element = {
          mode = "random",
          exclude = {
            "spectral"
          }
        },
        resistances = {
          randomCount = 1
        }
      },
      hasScript = false,
      source = "data/monster/monsters/skeleton_archer.ts",
      spells = {}
    },
    skeletonberserker = {
      name = "Skeleton Berserker",
      race = "undead",
      level = 86,
      damageModifier = {
        magic = 40,
        flame = 45,
        lightning = 50,
        cold = 55,
        poison = 40
      },
      enchantments = {
        "physical"
      },
      hasScript = false,
      source = "data/monster/monsters/skeleton_berserker.ts",
      spells = {}
    },
    skeleton4 = {
      name = "Skeleton Crusader",
      race = "blood",
      level = 75,
      damageModifier = {
        lightning = 65,
        cold = 45
      },
      hasScript = false,
      source = "data/monster/monsters/skeleton_crusader.ts",
      spells = {}
    },
    skeleton3 = {
      name = "Skeleton Guard",
      race = "undead",
      level = 40,
      hasScript = false,
      source = "data/monster/monsters/skeleton_guard.ts",
      spells = {}
    },
    skeletonscythe1 = {
      name = "Shadowveil Guardian",
      race = "undead",
      level = 86,
      damageModifier = {
        magic = 60,
        flame = 40,
        lightning = 30,
        cold = 30,
        poison = 30
      },
      hasScript = false,
      source = "data/monster/monsters/skeleton_guardian.ts",
      spells = {}
    },
    skeletontemplar2 = {
      name = "Skeleton Templar",
      race = "blood",
      level = 80,
      damageModifier = {
        magic = 100,
        flame = 80,
        lightning = 80,
        cold = 80,
        poison = 80
      },
      enchantments = {
        "magic",
        "flame"
      },
      hasScript = false,
      source = "data/monster/monsters/skeleton_templar.ts",
      spells = {}
    },
    skeleton2 = {
      name = "Skeleton Warrior",
      race = "undead",
      level = 16,
      hasScript = false,
      source = "data/monster/monsters/skeleton_warrior.ts",
      spells = {}
    },
    skeleton = {
      name = "Skeleton",
      race = "blood",
      level = 9,
      hasScript = false,
      source = "data/monster/monsters/skeleton.ts",
      spells = {}
    },
    skeletonaxe1 = {
      name = "Skeleton Axe",
      race = "blood",
      level = 76,
      damageModifier = {
        magic = 30,
        flame = 30,
        lightning = 30,
        cold = 30,
        poison = 30
      },
      hasScript = false,
      source = "data/monster/monsters/skeletonaxe1.ts",
      spells = {}
    },
    skeletonaxe2 = {
      name = "Skeleton Axe",
      race = "blood",
      level = 76,
      damageModifier = {
        magic = 30,
        flame = 75,
        lightning = 30,
        cold = 30,
        poison = 30
      },
      hasScript = false,
      source = "data/monster/monsters/skeletonaxe2.ts",
      spells = {}
    },
    snake = {
      name = "Snake",
      race = "venom",
      level = 9,
      spawnBehavior = {
        appearance = {
          rules = {
            {
              kind = "snake3",
              lookTypeId = 48,
              when = {
                requiredEnchantments = {
                  "poison"
                }
              }
            },
            {
              kind = "snake4",
              lookTypeId = 49,
              when = {
                requiredEnchantments = {
                  "flame"
                }
              }
            }
          }
        }
      },
      hasScript = false,
      source = "data/monster/monsters/snake.ts",
      spells = {
        {
          id = "monster-snake-acid-spit",
          source = "data/spells/monster/snakeAcidSpit.ts",
          targetMode = "target",
          combatType = 5,
          condition = {
            type = "poison",
            duration = 8000,
            damagePerTick = 8
          }
        }
      }
    },
    wraith2 = {
      name = "Spectral Wraith",
      race = "blood",
      level = 88,
      damageModifier = {
        magic = 30,
        flame = 50,
        lightning = 60,
        cold = 30
      },
      enchantments = {
        "spectral"
      },
      hasScript = false,
      source = "data/monster/monsters/spectral_wraith.ts",
      spells = {
        {
          id = "monster-wraith-haunt-bolt",
          source = "data/spells/monster/wraithHauntBolt.ts",
          targetMode = "target",
          combatType = 3,
          condition = {
            type = "freezing",
            duration = 4000,
            speedChange = -220
          },
          unsupportedConditionSpeedChange = -220
        }
      }
    },
    spectre = {
      name = "Spectre",
      race = "blood",
      level = 23,
      hasScript = false,
      source = "data/monster/monsters/spectre.ts",
      spells = {}
    },
    spider2 = {
      name = "Spellweaver Spider",
      race = "blood",
      level = 81,
      damageModifier = {
        magic = 100
      },
      enchantments = {
        "magic"
      },
      hasScript = false,
      source = "data/monster/monsters/spellweaver_spider.ts",
      spells = {}
    },
    spiderqueen = {
      name = "Spider Queen",
      race = "blood",
      level = 85,
      damageModifier = {
        magic = 50,
        flame = 60,
        lightning = 70,
        cold = 25,
        poison = 100
      },
      enchantments = {
        "poison",
        "curse-health"
      },
      spawnBehavior = {
        resistances = {
          randomCount = 3
        },
        enchantments = {
          extraRandomCount = 2
        }
      },
      hasScript = false,
      source = "data/monster/monsters/spider_queen.ts",
      spells = {}
    },
    spider = {
      name = "Spider",
      race = "venom",
      level = 81,
      damageModifier = {
        poison = 100
      },
      enchantments = {
        "poison"
      },
      spawnBehavior = {
        appearance = {
          rules = {
            {
              kind = "spider2",
              lookTypeId = 52,
              when = {
                requiredEnchantments = {
                  "magic"
                }
              }
            }
          }
        }
      },
      hasScript = false,
      source = "data/monster/monsters/spider.ts",
      spells = {}
    },
    templemob = {
      name = "Temple Mob",
      race = "blood",
      level = 76,
      hasScript = false,
      source = "data/monster/monsters/temple_mob.ts",
      spells = {}
    },
    goblin2 = {
      name = "Undead Goblin",
      race = "blood",
      level = 33,
      hasScript = false,
      source = "data/monster/monsters/undead_goblin.ts",
      spells = {}
    },
    rat2 = {
      name = "Undead Rat",
      race = "undead",
      level = 34,
      hasScript = false,
      source = "data/monster/monsters/undead_rat.ts",
      spells = {}
    },
    bat2 = {
      name = "Vampire Bat",
      race = "ice",
      level = 30,
      hasScript = false,
      source = "data/monster/monsters/vampire_bat.ts",
      spells = {}
    },
    snake3 = {
      name = "Venemous Snake",
      race = "venom",
      level = 82,
      damageModifier = {
        poison = 100
      },
      enchantments = {
        "poison"
      },
      hasScript = false,
      source = "data/monster/monsters/venemous_snake.ts",
      spells = {}
    },
    werewolf = {
      name = "Werewolf",
      race = "blood",
      level = 45,
      hasScript = false,
      source = "data/monster/monsters/werewolf.ts",
      spells = {}
    },
    wizard = {
      name = "Wizard",
      race = "blood",
      level = 1,
      hasScript = false,
      source = "data/monster/monsters/wizard.ts",
      spells = {}
    },
    wraith = {
      name = "Wraith",
      race = "ice",
      level = 50,
      spawnBehavior = {
        appearance = {
          rules = {
            {
              kind = "wraith2",
              lookTypeId = 60,
              when = {
                requiredEnchantments = {
                  "spectral"
                }
              }
            }
          }
        }
      },
      hasScript = false,
      source = "data/monster/monsters/wraith.ts",
      spells = {
        {
          id = "monster-wraith-haunt-bolt",
          source = "data/spells/monster/wraithHauntBolt.ts",
          targetMode = "target",
          combatType = 3,
          condition = {
            type = "freezing",
            duration = 4000,
            speedChange = -220
          },
          unsupportedConditionSpeedChange = -220
        }
      }
    },
    yeti = {
      name = "Yeti",
      race = "blood",
      level = 41,
      damageModifier = {
        cold = 100
      },
      hasScript = false,
      source = "data/monster/monsters/yeti.ts",
      spells = {}
    },
    zombie = {
      name = "Zombie",
      race = "undead",
      level = 49,
      spawnBehavior = {
        resistances = {
          randomCount = 0
        },
        enchantments = {
          fallbackRandomCount = 0,
          miniBossEnabled = false
        },
        respawn = {
          respawnOutsideArea = false
        }
      },
      hasScript = false,
      source = "data/monster/monsters/zombie.ts",
      spells = {}
    }
  },
}
