-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/bosses/shaman.ts
local mType = Game.createMonsterType("Zul'Gurak")
local monster = {}

monster.name = "Zul'Gurak"
monster.experience = 31646
monster.outfit = {
  lookType = 32,
}
monster.health = 18298
monster.maxHealth = 18298
monster.race = "blood"
monster.speed = 114
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
  boss = true,
}
monster.loot = {
  {id = 200, chance = 15000, maxCount = 1},
  {id = 209, chance = 9000, maxCount = 1},
  {id = 212, chance = 9000, maxCount = 1},
  {id = 157, chance = 9000, maxCount = 1},
  {id = 402, chance = 5000, maxCount = 1},
  {id = 403, chance = 5000, maxCount = 1},
  {id = 339, chance = 5000, maxCount = 1},
  {id = 311, chance = 5000, maxCount = 1},
  {id = 205, chance = 5000, maxCount = 1},
  {id = 208, chance = 5000, maxCount = 1},
  {id = 213, chance = 1000, maxCount = 1},
  {id = 214, chance = 1000, maxCount = 1},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -38,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 38,
  armor = 38,
}
monster.elements = {
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 60
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 60
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 30
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 30
  },
  {
    type = COMBAT_EARTHDAMAGE,
    percent = 30
  },
}

mType:register(monster)
