-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/bosses/butcher.ts
-- Source monster callbacks still need a dedicated Lua port.
local mType = Game.createMonsterType("Gorefiend the Butcher")
local monster = {}

monster.name = "Gorefiend the Butcher"
monster.experience = 24304
monster.outfit = {
  lookType = 4,
}
monster.health = 18298
monster.maxHealth = 18298
monster.race = "blood"
monster.speed = 114
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
  boss = true,
}
monster.loot = {
  {id = 249, chance = 6000, maxCount = 1},
  {id = 92, chance = 65000, maxCount = 600},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -1083,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 44,
  armor = 44,
}
monster.elements = {
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 50
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 100
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 70
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 25
  },
  {
    type = COMBAT_EARTHDAMAGE,
    percent = 40
  },
}

mType:register(monster)
