-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/bosses/skeleton_king.ts
local mType = Game.createMonsterType("Skeleton King")
local monster = {}

monster.name = "Skeleton King"
monster.experience = 1100
monster.outfit = {
  lookType = 3,
}
monster.health = 901
monster.maxHealth = 901
monster.race = "undead"
monster.speed = 200
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
  boss = true,
}
monster.loot = {
  {id = 66, chance = 40000, maxCount = 1},
  {id = 330, chance = 35000, maxCount = 1},
  {id = 123, chance = 100000, maxCount = 1},
}
monster.attacks = {
  {
    name = "melee",
    interval = 1200,
    minDamage = -70,
    maxDamage = -20
  },
}
monster.defenses = {
  defense = 5,
  armor = 5,
}
monster.elements = {
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 50
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 50
  },
}

mType:register(monster)
