-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/bosses/skeleton_templar.ts
local mType = Game.createMonsterType("Skeleton Templar")
local monster = {}

monster.name = "Skeleton Templar"
monster.experience = 44304
monster.outfit = {
  lookType = 44,
}
monster.health = 6099
monster.maxHealth = 6099
monster.race = "blood"
monster.speed = 114
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
  boss = true,
}
monster.loot = {
  {id = 286, chance = 1000, maxCount = 1},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -3314,
    maxDamage = -637
  },
}
monster.defenses = {
  defense = 34,
  armor = 34,
}
monster.elements = {
  {
    type = COMBAT_UNDEFINEDDAMAGE,
    percent = 80
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 80
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 80
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 80
  },
  {
    type = COMBAT_EARTHDAMAGE,
    percent = 100
  },
}

mType:register(monster)
