-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/bosses/worm.ts
local mType = Game.createMonsterType("Shai-Hulud")
local monster = {}

monster.name = "Shai-Hulud"
monster.experience = 13924
monster.outfit = {
  lookType = 58,
}
monster.health = 21348
monster.maxHealth = 21348
monster.race = "blood"
monster.speed = 62
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
  boss = true,
}
monster.loot = {
  {id = 288, chance = 100000, maxCount = 1},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -1976,
    maxDamage = -127
  },
}
monster.defenses = {
  defense = 40,
  armor = 40,
}
monster.elements = {
  {
    type = COMBAT_UNDEFINEDDAMAGE,
    percent = 70
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 55
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 60
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 60
  },
  {
    type = COMBAT_EARTHDAMAGE,
    percent = 40
  },
}

mType:register(monster)
