-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/ghost.ts
local mType = Game.createMonsterType("Ghost")
local monster = {}

monster.name = "Ghost"
monster.experience = 4922
monster.outfit = {
  lookType = 13,
}
monster.health = 1997
monster.maxHealth = 1997
monster.race = "blood"
monster.speed = 138
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 15000, maxCount = 1},
  {id = 200, chance = 3000, maxCount = 1},
  {id = 209, chance = 2000, maxCount = 1},
  {id = 212, chance = 2000, maxCount = 1},
  {id = 156, chance = 2000, maxCount = 1},
  {id = 338, chance = 2000, maxCount = 1},
  {id = 228, chance = 2000, maxCount = 1},
  {id = 197, chance = 2000, maxCount = 1},
  {id = 92, chance = 90000, maxCount = 100},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -35,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 30,
  armor = 30,
}
monster.elements = {
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 60
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 20
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 30
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 30
  },
}

mType:register(monster)
