-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/goblin.ts
local mType = Game.createMonsterType("Goblin")
local monster = {}

monster.name = "Goblin"
monster.experience = 9
monster.outfit = {
  lookType = 14,
}
monster.health = 117
monster.maxHealth = 117
monster.race = "blood"
monster.speed = 160
monster.runHealth = 0
monster.changeTarget = {
  interval = 4000,
  chance = 10,
}
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 35, chance = 20000, maxCount = 1},
  {id = 63, chance = 10000, maxCount = 1},
  {id = 38, chance = 5000, maxCount = 1},
  {id = 74, chance = 10000, maxCount = 1},
  {id = 75, chance = 15000, maxCount = 1},
  {id = 80, chance = 5000, maxCount = 1},
  {id = 85, chance = 5000, maxCount = 1},
  {id = 144, chance = 5000, maxCount = 1},
  {id = 92, chance = 15000, maxCount = 10},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -6,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 2,
  armor = 2,
}

mType:register(monster)
