-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/kobold.ts
local mType = Game.createMonsterType("Kobold")
local monster = {}

monster.name = "Kobold"
monster.experience = 8467
monster.outfit = {
  lookType = 18,
}
monster.health = 1898
monster.maxHealth = 1898
monster.race = "blood"
monster.speed = 64
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 30000, maxCount = 1},
  {id = 200, chance = 9000, maxCount = 4},
  {id = 209, chance = 20000, maxCount = 1},
  {id = 212, chance = 20000, maxCount = 1},
  {id = 154, chance = 2000, maxCount = 1},
  {id = 207, chance = 2000, maxCount = 1},
  {id = 336, chance = 2000, maxCount = 1},
  {id = 195, chance = 2000, maxCount = 1},
  {id = 92, chance = 90000, maxCount = 110},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -362,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 32,
  armor = 32,
}
monster.elements = {
  {
    type = COMBAT_UNDEFINEDDAMAGE,
    percent = 40
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 60
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 80
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 20
  },
}

mType:register(monster)
