-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/mage.ts
local mType = Game.createMonsterType("Mage")
local monster = {}

monster.name = "Mage"
monster.experience = 11425
monster.outfit = {
  lookType = 19,
}
monster.health = 2079
monster.maxHealth = 2079
monster.race = "blood"
monster.speed = 66
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 4,
}
monster.loot = {
  {id = 110, chance = 15000, maxCount = 1},
  {id = 200, chance = 3000, maxCount = 1},
  {id = 209, chance = 2000, maxCount = 1},
  {id = 212, chance = 2000, maxCount = 1},
  {id = 157, chance = 3000, maxCount = 1},
  {id = 402, chance = 3000, maxCount = 1},
  {id = 403, chance = 3000, maxCount = 1},
  {id = 339, chance = 3000, maxCount = 1},
  {id = 311, chance = 3000, maxCount = 1},
  {id = 205, chance = 3000, maxCount = 1},
  {id = 208, chance = 3000, maxCount = 1},
  {id = 92, chance = 90000, maxCount = 136},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -822,
    maxDamage = 0
  },
  {
    name = "combat",
    type = COMBAT_ENERGYDAMAGE,
    chance = 28,
    interval = 2200,
    target = true,
    range = 5,
    minDamage = -323,
    maxDamage = -162,
    effect = 1
  },
  {
    name = "combat",
    type = COMBAT_FIREDAMAGE,
    chance = 16,
    interval = 3200,
    target = true,
    range = 4,
    minDamage = -264,
    maxDamage = -132,
    effect = 2,
    radius = 1
  },
}
monster.defenses = {
  defense = 30,
  armor = 30,
}
monster.elements = {
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 50
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 50
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 50
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 50
  },
  {
    type = COMBAT_EARTHDAMAGE,
    percent = 50
  },
}

mType:register(monster)
