-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/oculothorax.ts
local mType = Game.createMonsterType("Oculothorax")
local monster = {}

monster.name = "Oculothorax"
monster.experience = 4997
monster.outfit = {
  lookType = 27,
}
monster.health = 1723
monster.maxHealth = 1723
monster.race = "blood"
monster.speed = 97
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 30000, maxCount = 1},
  {id = 200, chance = 3000, maxCount = 1},
  {id = 209, chance = 2000, maxCount = 1},
  {id = 212, chance = 2000, maxCount = 1},
  {id = 336, chance = 1000, maxCount = 1},
  {id = 154, chance = 1000, maxCount = 1},
  {id = 207, chance = 1000, maxCount = 1},
  {id = 195, chance = 1000, maxCount = 1},
  {id = 335, chance = 1000, maxCount = 1},
  {id = 152, chance = 1000, maxCount = 1},
  {id = 128, chance = 1000, maxCount = 1},
  {id = 201, chance = 1000, maxCount = 1},
  {id = 199, chance = 1000, maxCount = 1},
  {id = 92, chance = 90000, maxCount = 120},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -1322,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 30,
  armor = 30,
}
monster.elements = {
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 40
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 100
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 80
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 40
  },
}

mType:register(monster)
