-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/skeleton_archer.ts
local mType = Game.createMonsterType("Skeleton Archer")
local monster = {}

monster.name = "Skeleton Archer"
monster.experience = 14552
monster.outfit = {
  lookType = 37,
}
monster.health = 1766
monster.maxHealth = 1766
monster.race = "blood"
monster.speed = 74
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 20000, maxCount = 1},
  {id = 200, chance = 7000, maxCount = 3},
  {id = 209, chance = 3000, maxCount = 1},
  {id = 212, chance = 3000, maxCount = 1},
  {id = 92, chance = 12000, maxCount = 90},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -38,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 24,
  armor = 24,
}
monster.elements = {
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 40
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 45
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 50
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 55
  },
  {
    type = COMBAT_EARTHDAMAGE,
    percent = 40
  },
}

mType:register(monster)
