-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/skeleton_guard.ts
local mType = Game.createMonsterType("Skeleton Guard")
local monster = {}

monster.name = "Skeleton Guard"
monster.experience = 500
monster.outfit = {
  lookType = 35,
}
monster.health = 500
monster.maxHealth = 500
monster.race = "undead"
monster.speed = 210
monster.runHealth = 0
monster.changeTarget = {
  interval = 5000,
  chance = 0,
}
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 65000, maxCount = 1},
  {id = 76, chance = 5000, maxCount = 1},
  {id = 83, chance = 3000, maxCount = 1},
  {id = 141, chance = 1000, maxCount = 1},
  {id = 332, chance = 3000, maxCount = 1},
  {id = 82, chance = 2000, maxCount = 1},
  {id = 113, chance = 1000, maxCount = 1},
  {id = 149, chance = 2000, maxCount = 1},
  {id = 92, chance = 10000, maxCount = 1},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -100,
    maxDamage = -20
  },
}
monster.defenses = {
  defense = 9,
  armor = 9,
}

mType:register(monster)
