-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/snake.ts
local mType = Game.createMonsterType("Snake")
local monster = {}

monster.name = "Snake"
monster.experience = 23
monster.outfit = {
  lookType = 46,
}
monster.health = 162
monster.maxHealth = 162
monster.race = "venom"
monster.speed = 167
monster.runHealth = 5
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 35, chance = 30000, maxCount = 1},
  {id = 23, chance = 10000, maxCount = 1},
  {id = 327, chance = 10000, maxCount = 1},
  {id = 38, chance = 5000, maxCount = 1},
  {id = 75, chance = 20000, maxCount = 1},
  {id = 81, chance = 2000, maxCount = 1},
  {id = 144, chance = 5000, maxCount = 1},
  {id = 92, chance = 13000, maxCount = 25},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -14,
    maxDamage = 0
  },
  {
    name = "combat",
    type = COMBAT_EARTHDAMAGE,
    chance = 18,
    interval = 2500,
    target = true,
    range = 4,
    minDamage = -18,
    maxDamage = -10,
    effect = 144,
    condition = {
      type = CONDITION_POISON,
      duration = 8000,
      minDamage = 8,
      maxDamage = 8,
      interval = 1000
    },
    duration = 8000
  },
}
monster.defenses = {
  defense = 3,
  armor = 3,
}

mType:register(monster)
