-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/spectre.ts
local mType = Game.createMonsterType("Spectre")
local monster = {}

monster.name = "Spectre"
monster.experience = 58
monster.outfit = {
  lookType = 50,
}
monster.health = 296
monster.maxHealth = 296
monster.race = "blood"
monster.speed = 255
monster.runHealth = 0
monster.changeTarget = {
  interval = 5000,
  chance = 0,
}
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 35, chance = 25000, maxCount = 1},
  {id = 65, chance = 15000, maxCount = 1},
  {id = 38, chance = 5000, maxCount = 1},
  {id = 75, chance = 20000, maxCount = 1},
  {id = 81, chance = 4000, maxCount = 1},
  {id = 86, chance = 3000, maxCount = 1},
  {id = 112, chance = 2000, maxCount = 1},
  {id = 146, chance = 5000, maxCount = 1},
  {id = 92, chance = 12000, maxCount = 19},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -22,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 2,
  armor = 2,
}

mType:register(monster)
