-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/spider_queen.ts
local mType = Game.createMonsterType("Spider Queen")
local monster = {}

monster.name = "Spider Queen"
monster.experience = 4987
monster.outfit = {
  lookType = 53,
}
monster.health = 12199
monster.maxHealth = 12199
monster.race = "blood"
monster.speed = 78
monster.runHealth = 25
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
  boss = true,
}
monster.loot = {
  {id = 200, chance = 8000, maxCount = 1},
  {id = 209, chance = 5000, maxCount = 1},
  {id = 212, chance = 5000, maxCount = 1},
  {id = 111, chance = 33000, maxCount = 1},
  {id = 156, chance = 5000, maxCount = 1},
  {id = 338, chance = 5000, maxCount = 1},
  {id = 228, chance = 5000, maxCount = 1},
  {id = 197, chance = 5000, maxCount = 1},
  {id = 92, chance = 12000, maxCount = 70},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -33,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 38,
  armor = 38,
}
monster.elements = {
  {
    type = COMBAT_UNDEFINEDDAMAGE,
    percent = 50
  },
  {
    type = COMBAT_FIREDAMAGE,
    percent = 60
  },
  {
    type = COMBAT_ENERGYDAMAGE,
    percent = 70
  },
  {
    type = COMBAT_ICEDAMAGE,
    percent = 25
  },
  {
    type = COMBAT_EARTHDAMAGE,
    percent = 100
  },
}

mType:register(monster)
