-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/venemous_snake.ts
local mType = Game.createMonsterType("Venemous Snake")
local monster = {}

monster.name = "Venemous Snake"
monster.experience = 988
monster.outfit = {
  lookType = 48,
}
monster.health = 1462
monster.maxHealth = 1462
monster.race = "venom"
monster.speed = 63
monster.runHealth = 20
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 110, chance = 20000, maxCount = 1},
  {id = 200, chance = 3000, maxCount = 1},
  {id = 209, chance = 2000, maxCount = 1},
  {id = 212, chance = 2000, maxCount = 1},
  {id = 154, chance = 2000, maxCount = 1},
  {id = 207, chance = 2000, maxCount = 1},
  {id = 336, chance = 2000, maxCount = 1},
  {id = 195, chance = 2000, maxCount = 1},
  {id = 92, chance = 10000, maxCount = 10},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -33,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 25,
  armor = 25,
}
monster.elements = {
  {
    type = COMBAT_EARTHDAMAGE,
    percent = 100
  },
}

mType:register(monster)
