-- Generated by tools/export_content.mjs. Do not edit by hand.
-- Source: data/monster/monsters/wizard.ts
local mType = Game.createMonsterType("Wizard")
local monster = {}

monster.name = "Wizard"
monster.experience = 6
monster.outfit = {
  lookType = 57,
}
monster.health = 91
monster.maxHealth = 91
monster.race = "blood"
monster.speed = 92
monster.runHealth = 0
monster.flags = {
  attackable = true,
  hostile = true,
  targetDistance = 1,
}
monster.loot = {
  {id = 35, chance = 100000, maxCount = 1},
}
monster.attacks = {
  {
    name = "melee",
    interval = 2000,
    minDamage = -28,
    maxDamage = 0
  },
}
monster.defenses = {
  defense = 2,
  armor = 2,
}

mType:register(monster)
